// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Thalassa
{
    /// <summary>
    /// Create a database backup schedule
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Thalassa = Pulumi.Thalassa;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     // Create a VPC for the database cluster
    ///     var example = new Thalassa.Vpc("example", new()
    ///     {
    ///         Name = "example-vpc",
    ///         Description = "Example VPC for database cluster",
    ///         Region = "nl-01",
    ///         Cidrs = new[]
    ///         {
    ///             "10.0.0.0/16",
    ///         },
    ///     });
    /// 
    ///     // Create a subnet for the database cluster
    ///     var exampleSubnet = new Thalassa.Subnet("example", new()
    ///     {
    ///         Name = "example-subnet",
    ///         Description = "Example subnet for database cluster",
    ///         VpcId = example.Id,
    ///         Cidr = "10.0.1.0/24",
    ///     });
    /// 
    ///     // Create a database cluster for the backup schedule
    ///     var exampleDbaasDbCluster = new Thalassa.DbaasDbCluster("example", new()
    ///     {
    ///         Name = "example-db-cluster",
    ///         Description = "Example database cluster for backup schedule",
    ///         SubnetId = exampleSubnet.Id,
    ///         DatabaseInstanceType = "db-pgp-small",
    ///         Engine = "postgres",
    ///         EngineVersion = "15.13",
    ///         AllocatedStorage = 100,
    ///         VolumeTypeClass = "block",
    ///     });
    /// 
    ///     // Create a database backup schedule with Thalassa default values
    ///     var exampleDbaasDbBackupschedule = new Thalassa.DbaasDbBackupschedule("example", new()
    ///     {
    ///         DbClusterId = exampleDbaasDbCluster.Id,
    ///         Name = "example-backup-schedule",
    ///         Schedule = "0 2 * * *",
    ///         RetentionPolicy = "7d",
    ///     });
    /// 
    ///     return new Dictionary&lt;string, object?&gt;
    ///     {
    ///         ["backupScheduleId"] = exampleDbaasDbBackupschedule.Id,
    ///         ["backupScheduleName"] = exampleDbaasDbBackupschedule.Name,
    ///     };
    /// });
    /// ```
    /// </summary>
    [ThalassaResourceType("thalassa:index/dbaasDbBackupschedule:DbaasDbBackupschedule")]
    public partial class DbaasDbBackupschedule : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The annotations of the database backup schedule
        /// </summary>
        [Output("annotations")]
        public Output<ImmutableDictionary<string, string>?> Annotations { get; private set; } = null!;

        /// <summary>
        /// The ID of the database cluster
        /// </summary>
        [Output("dbClusterId")]
        public Output<string> DbClusterId { get; private set; } = null!;

        /// <summary>
        /// The description of the database backup schedule
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// The labels of the database backup schedule
        /// </summary>
        [Output("labels")]
        public Output<ImmutableDictionary<string, string>?> Labels { get; private set; } = null!;

        /// <summary>
        /// The method of the backup schedule (barman)
        /// </summary>
        [Output("method")]
        public Output<string?> Method { get; private set; } = null!;

        /// <summary>
        /// The name of the database backup schedule
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Reference to the Organisation of the Db Backup Schedule. If not provided, the organisation of the (Terraform) provider will be used.
        /// </summary>
        [Output("organisationId")]
        public Output<string?> OrganisationId { get; private set; } = null!;

        /// <summary>
        /// The retention policy of the database backup schedule (7d, 14d, 30d, 90d, 180d, 365d, 730d)
        /// </summary>
        [Output("retentionPolicy")]
        public Output<string?> RetentionPolicy { get; private set; } = null!;

        /// <summary>
        /// The cron schedule of the database backup schedule (0 0 * * *)
        /// </summary>
        [Output("schedule")]
        public Output<string?> Schedule { get; private set; } = null!;

        /// <summary>
        /// Whether the database backup schedule is suspended
        /// </summary>
        [Output("suspended")]
        public Output<bool?> Suspended { get; private set; } = null!;


        /// <summary>
        /// Create a DbaasDbBackupschedule resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public DbaasDbBackupschedule(string name, DbaasDbBackupscheduleArgs args, CustomResourceOptions? options = null)
            : base("thalassa:index/dbaasDbBackupschedule:DbaasDbBackupschedule", name, args ?? new DbaasDbBackupscheduleArgs(), MakeResourceOptions(options, ""))
        {
        }

        private DbaasDbBackupschedule(string name, Input<string> id, DbaasDbBackupscheduleState? state = null, CustomResourceOptions? options = null)
            : base("thalassa:index/dbaasDbBackupschedule:DbaasDbBackupschedule", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/sandervb2/pulumi-thalassa",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing DbaasDbBackupschedule resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static DbaasDbBackupschedule Get(string name, Input<string> id, DbaasDbBackupscheduleState? state = null, CustomResourceOptions? options = null)
        {
            return new DbaasDbBackupschedule(name, id, state, options);
        }
    }

    public sealed class DbaasDbBackupscheduleArgs : global::Pulumi.ResourceArgs
    {
        [Input("annotations")]
        private InputMap<string>? _annotations;

        /// <summary>
        /// The annotations of the database backup schedule
        /// </summary>
        public InputMap<string> Annotations
        {
            get => _annotations ?? (_annotations = new InputMap<string>());
            set => _annotations = value;
        }

        /// <summary>
        /// The ID of the database cluster
        /// </summary>
        [Input("dbClusterId", required: true)]
        public Input<string> DbClusterId { get; set; } = null!;

        /// <summary>
        /// The description of the database backup schedule
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("labels")]
        private InputMap<string>? _labels;

        /// <summary>
        /// The labels of the database backup schedule
        /// </summary>
        public InputMap<string> Labels
        {
            get => _labels ?? (_labels = new InputMap<string>());
            set => _labels = value;
        }

        /// <summary>
        /// The method of the backup schedule (barman)
        /// </summary>
        [Input("method")]
        public Input<string>? Method { get; set; }

        /// <summary>
        /// The name of the database backup schedule
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Reference to the Organisation of the Db Backup Schedule. If not provided, the organisation of the (Terraform) provider will be used.
        /// </summary>
        [Input("organisationId")]
        public Input<string>? OrganisationId { get; set; }

        /// <summary>
        /// The retention policy of the database backup schedule (7d, 14d, 30d, 90d, 180d, 365d, 730d)
        /// </summary>
        [Input("retentionPolicy")]
        public Input<string>? RetentionPolicy { get; set; }

        /// <summary>
        /// The cron schedule of the database backup schedule (0 0 * * *)
        /// </summary>
        [Input("schedule")]
        public Input<string>? Schedule { get; set; }

        /// <summary>
        /// Whether the database backup schedule is suspended
        /// </summary>
        [Input("suspended")]
        public Input<bool>? Suspended { get; set; }

        public DbaasDbBackupscheduleArgs()
        {
        }
        public static new DbaasDbBackupscheduleArgs Empty => new DbaasDbBackupscheduleArgs();
    }

    public sealed class DbaasDbBackupscheduleState : global::Pulumi.ResourceArgs
    {
        [Input("annotations")]
        private InputMap<string>? _annotations;

        /// <summary>
        /// The annotations of the database backup schedule
        /// </summary>
        public InputMap<string> Annotations
        {
            get => _annotations ?? (_annotations = new InputMap<string>());
            set => _annotations = value;
        }

        /// <summary>
        /// The ID of the database cluster
        /// </summary>
        [Input("dbClusterId")]
        public Input<string>? DbClusterId { get; set; }

        /// <summary>
        /// The description of the database backup schedule
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("labels")]
        private InputMap<string>? _labels;

        /// <summary>
        /// The labels of the database backup schedule
        /// </summary>
        public InputMap<string> Labels
        {
            get => _labels ?? (_labels = new InputMap<string>());
            set => _labels = value;
        }

        /// <summary>
        /// The method of the backup schedule (barman)
        /// </summary>
        [Input("method")]
        public Input<string>? Method { get; set; }

        /// <summary>
        /// The name of the database backup schedule
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Reference to the Organisation of the Db Backup Schedule. If not provided, the organisation of the (Terraform) provider will be used.
        /// </summary>
        [Input("organisationId")]
        public Input<string>? OrganisationId { get; set; }

        /// <summary>
        /// The retention policy of the database backup schedule (7d, 14d, 30d, 90d, 180d, 365d, 730d)
        /// </summary>
        [Input("retentionPolicy")]
        public Input<string>? RetentionPolicy { get; set; }

        /// <summary>
        /// The cron schedule of the database backup schedule (0 0 * * *)
        /// </summary>
        [Input("schedule")]
        public Input<string>? Schedule { get; set; }

        /// <summary>
        /// Whether the database backup schedule is suspended
        /// </summary>
        [Input("suspended")]
        public Input<bool>? Suspended { get; set; }

        public DbaasDbBackupscheduleState()
        {
        }
        public static new DbaasDbBackupscheduleState Empty => new DbaasDbBackupscheduleState();
    }
}
