// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Thalassa
{
    public static class GetDbaasDbBackupschedule
    {
        public static Task<GetDbaasDbBackupscheduleResult> InvokeAsync(GetDbaasDbBackupscheduleArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetDbaasDbBackupscheduleResult>("thalassa:index/getDbaasDbBackupschedule:getDbaasDbBackupschedule", args ?? new GetDbaasDbBackupscheduleArgs(), options.WithDefaults());

        public static Output<GetDbaasDbBackupscheduleResult> Invoke(GetDbaasDbBackupscheduleInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetDbaasDbBackupscheduleResult>("thalassa:index/getDbaasDbBackupschedule:getDbaasDbBackupschedule", args ?? new GetDbaasDbBackupscheduleInvokeArgs(), options.WithDefaults());

        public static Output<GetDbaasDbBackupscheduleResult> Invoke(GetDbaasDbBackupscheduleInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetDbaasDbBackupscheduleResult>("thalassa:index/getDbaasDbBackupschedule:getDbaasDbBackupschedule", args ?? new GetDbaasDbBackupscheduleInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetDbaasDbBackupscheduleArgs : global::Pulumi.InvokeArgs
    {
        [Input("dbClusterId", required: true)]
        public string DbClusterId { get; set; } = null!;

        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        [Input("organisationId")]
        public string? OrganisationId { get; set; }

        public GetDbaasDbBackupscheduleArgs()
        {
        }
        public static new GetDbaasDbBackupscheduleArgs Empty => new GetDbaasDbBackupscheduleArgs();
    }

    public sealed class GetDbaasDbBackupscheduleInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("dbClusterId", required: true)]
        public Input<string> DbClusterId { get; set; } = null!;

        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("organisationId")]
        public Input<string>? OrganisationId { get; set; }

        public GetDbaasDbBackupscheduleInvokeArgs()
        {
        }
        public static new GetDbaasDbBackupscheduleInvokeArgs Empty => new GetDbaasDbBackupscheduleInvokeArgs();
    }


    [OutputType]
    public sealed class GetDbaasDbBackupscheduleResult
    {
        public readonly string BackupTarget;
        public readonly string DbClusterId;
        /// <summary>
        /// The ID of this resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly string? OrganisationId;
        public readonly string RetentionPolicy;
        public readonly string Schedule;
        public readonly bool Suspended;

        [OutputConstructor]
        private GetDbaasDbBackupscheduleResult(
            string backupTarget,

            string dbClusterId,

            string id,

            string name,

            string? organisationId,

            string retentionPolicy,

            string schedule,

            bool suspended)
        {
            BackupTarget = backupTarget;
            DbClusterId = dbClusterId;
            Id = id;
            Name = name;
            OrganisationId = organisationId;
            RetentionPolicy = retentionPolicy;
            Schedule = schedule;
            Suspended = suspended;
        }
    }
}
