// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Thalassa
{
    /// <summary>
    /// Manage access credentials for a service account in Thalassa Cloud
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Thalassa = Pulumi.Thalassa;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     // Create a service account first
    ///     var example = new Thalassa.IamServiceAccount("example", new()
    ///     {
    ///         Name = "example-service-account",
    ///         Description = "An example service account for demonstration purposes",
    ///         Labels = 
    ///         {
    ///             { "environment", "development" },
    ///             { "project", "example" },
    ///             { "type", "automation" },
    ///         },
    ///     });
    /// 
    ///     // Create access credentials for the service account
    ///     var apiCredential = new Thalassa.IamServiceAccountAccessCredential("api_credential", new()
    ///     {
    ///         ServiceAccountId = example.Id,
    ///         Scopes = new[]
    ///         {
    ///             "api:read",
    ///             "api:write",
    ///         },
    ///     });
    /// 
    ///     // Create object storage access credentials
    ///     var storageCredential = new Thalassa.IamServiceAccountAccessCredential("storage_credential", new()
    ///     {
    ///         ServiceAccountId = example.Id,
    ///         Scopes = new[]
    ///         {
    ///             "objectStorage",
    ///         },
    ///     });
    /// 
    ///     return new Dictionary&lt;string, object?&gt;
    ///     {
    ///         ["apiCredentialId"] = apiCredential.Id,
    ///         ["apiCredentialAccessKey"] = apiCredential.AccessKey,
    ///         ["apiCredentialAccessSecret"] = apiCredential.AccessSecret,
    ///         ["storageCredentialId"] = storageCredential.Id,
    ///     };
    /// });
    /// ```
    /// </summary>
    [ThalassaResourceType("thalassa:index/iamServiceAccountAccessCredential:IamServiceAccountAccessCredential")]
    public partial class IamServiceAccountAccessCredential : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Access key for the credential
        /// </summary>
        [Output("accessKey")]
        public Output<string> AccessKey { get; private set; } = null!;

        /// <summary>
        /// Access secret for the credential
        /// </summary>
        [Output("accessSecret")]
        public Output<string> AccessSecret { get; private set; } = null!;

        /// <summary>
        /// Creation timestamp of the access credential
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// Expiration timestamp of the access credential (RFC3339 format)
        /// </summary>
        [Output("expiresAt")]
        public Output<string?> ExpiresAt { get; private set; } = null!;

        /// <summary>
        /// Last used timestamp of the access credential
        /// </summary>
        [Output("lastUsedAt")]
        public Output<string> LastUsedAt { get; private set; } = null!;

        /// <summary>
        /// List of scopes for the access credential
        /// </summary>
        [Output("scopes")]
        public Output<ImmutableArray<string>> Scopes { get; private set; } = null!;

        /// <summary>
        /// Identity of the service account
        /// </summary>
        [Output("serviceAccountId")]
        public Output<string> ServiceAccountId { get; private set; } = null!;


        /// <summary>
        /// Create a IamServiceAccountAccessCredential resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public IamServiceAccountAccessCredential(string name, IamServiceAccountAccessCredentialArgs args, CustomResourceOptions? options = null)
            : base("thalassa:index/iamServiceAccountAccessCredential:IamServiceAccountAccessCredential", name, args ?? new IamServiceAccountAccessCredentialArgs(), MakeResourceOptions(options, ""))
        {
        }

        private IamServiceAccountAccessCredential(string name, Input<string> id, IamServiceAccountAccessCredentialState? state = null, CustomResourceOptions? options = null)
            : base("thalassa:index/iamServiceAccountAccessCredential:IamServiceAccountAccessCredential", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/sandervb2/pulumi-thalassa",
                AdditionalSecretOutputs =
                {
                    "accessKey",
                    "accessSecret",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing IamServiceAccountAccessCredential resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static IamServiceAccountAccessCredential Get(string name, Input<string> id, IamServiceAccountAccessCredentialState? state = null, CustomResourceOptions? options = null)
        {
            return new IamServiceAccountAccessCredential(name, id, state, options);
        }
    }

    public sealed class IamServiceAccountAccessCredentialArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Expiration timestamp of the access credential (RFC3339 format)
        /// </summary>
        [Input("expiresAt")]
        public Input<string>? ExpiresAt { get; set; }

        [Input("scopes")]
        private InputList<string>? _scopes;

        /// <summary>
        /// List of scopes for the access credential
        /// </summary>
        public InputList<string> Scopes
        {
            get => _scopes ?? (_scopes = new InputList<string>());
            set => _scopes = value;
        }

        /// <summary>
        /// Identity of the service account
        /// </summary>
        [Input("serviceAccountId", required: true)]
        public Input<string> ServiceAccountId { get; set; } = null!;

        public IamServiceAccountAccessCredentialArgs()
        {
        }
        public static new IamServiceAccountAccessCredentialArgs Empty => new IamServiceAccountAccessCredentialArgs();
    }

    public sealed class IamServiceAccountAccessCredentialState : global::Pulumi.ResourceArgs
    {
        [Input("accessKey")]
        private Input<string>? _accessKey;

        /// <summary>
        /// Access key for the credential
        /// </summary>
        public Input<string>? AccessKey
        {
            get => _accessKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _accessKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("accessSecret")]
        private Input<string>? _accessSecret;

        /// <summary>
        /// Access secret for the credential
        /// </summary>
        public Input<string>? AccessSecret
        {
            get => _accessSecret;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _accessSecret = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Creation timestamp of the access credential
        /// </summary>
        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        /// <summary>
        /// Expiration timestamp of the access credential (RFC3339 format)
        /// </summary>
        [Input("expiresAt")]
        public Input<string>? ExpiresAt { get; set; }

        /// <summary>
        /// Last used timestamp of the access credential
        /// </summary>
        [Input("lastUsedAt")]
        public Input<string>? LastUsedAt { get; set; }

        [Input("scopes")]
        private InputList<string>? _scopes;

        /// <summary>
        /// List of scopes for the access credential
        /// </summary>
        public InputList<string> Scopes
        {
            get => _scopes ?? (_scopes = new InputList<string>());
            set => _scopes = value;
        }

        /// <summary>
        /// Identity of the service account
        /// </summary>
        [Input("serviceAccountId")]
        public Input<string>? ServiceAccountId { get; set; }

        public IamServiceAccountAccessCredentialState()
        {
        }
        public static new IamServiceAccountAccessCredentialState Empty => new IamServiceAccountAccessCredentialState();
    }
}
