// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Thalassa
{
    /// <summary>
    /// Manage a secret version in Thalassa Secrets Manager
    /// 
    /// &gt; **Early access:** Secrets Manager is in early access. The API and Terraform resource schema may change in future provider releases.
    /// 
    /// See [Secrets Manager documentation](https://docs.thalassa.cloud/docs/secrets-manager/).
    /// 
    /// Stores a new secret version via `PutSecretValue`. Plaintext is not returned on read.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Thalassa = Pulumi.Thalassa;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var dbPassword = new Thalassa.SecretVersion("db_password", new()
    ///     {
    ///         Region = "nl-01",
    ///         Path = dbPasswordThalassaSecret.Path,
    ///         SecretString = "initial-password",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// Import ID format: `{region}{path}/{version}` (e.g. `nl-01/app/prod/db/password/3`).
    /// 
    /// !/bin/bash
    /// Example: terraform import thalassa_secret_version.db_password nl-01/app/prod/db/password/3
    /// 
    /// ```sh
    /// $ pulumi import thalassa:index/secretVersion:SecretVersion db_password nl-01/app/prod/db/password/3
    /// ```
    /// </summary>
    [ThalassaResourceType("thalassa:index/secretVersion:SecretVersion")]
    public partial class SecretVersion : global::Pulumi.CustomResource
    {
        [Output("generateSecret")]
        public Output<Outputs.SecretVersionGenerateSecret?> GenerateSecret { get; private set; } = null!;

        [Output("organisationId")]
        public Output<string?> OrganisationId { get; private set; } = null!;

        [Output("path")]
        public Output<string> Path { get; private set; } = null!;

        [Output("region")]
        public Output<string> Region { get; private set; } = null!;

        [Output("secretKeyValues")]
        public Output<ImmutableDictionary<string, string>?> SecretKeyValues { get; private set; } = null!;

        /// <summary>
        /// Secret string value (not returned on read).
        /// </summary>
        [Output("secretString")]
        public Output<string?> SecretString { get; private set; } = null!;

        /// <summary>
        /// Version number assigned by the platform.
        /// </summary>
        [Output("version")]
        public Output<int> Version { get; private set; } = null!;


        /// <summary>
        /// Create a SecretVersion resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public SecretVersion(string name, SecretVersionArgs args, CustomResourceOptions? options = null)
            : base("thalassa:index/secretVersion:SecretVersion", name, args ?? new SecretVersionArgs(), MakeResourceOptions(options, ""))
        {
        }

        private SecretVersion(string name, Input<string> id, SecretVersionState? state = null, CustomResourceOptions? options = null)
            : base("thalassa:index/secretVersion:SecretVersion", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/sandervb2/pulumi-thalassa",
                AdditionalSecretOutputs =
                {
                    "secretKeyValues",
                    "secretString",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing SecretVersion resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static SecretVersion Get(string name, Input<string> id, SecretVersionState? state = null, CustomResourceOptions? options = null)
        {
            return new SecretVersion(name, id, state, options);
        }
    }

    public sealed class SecretVersionArgs : global::Pulumi.ResourceArgs
    {
        [Input("generateSecret")]
        public Input<Inputs.SecretVersionGenerateSecretArgs>? GenerateSecret { get; set; }

        [Input("organisationId")]
        public Input<string>? OrganisationId { get; set; }

        [Input("path", required: true)]
        public Input<string> Path { get; set; } = null!;

        [Input("region", required: true)]
        public Input<string> Region { get; set; } = null!;

        [Input("secretKeyValues")]
        private InputMap<string>? _secretKeyValues;
        public InputMap<string> SecretKeyValues
        {
            get => _secretKeyValues ?? (_secretKeyValues = new InputMap<string>());
            set
            {
                var emptySecret = Output.CreateSecret(ImmutableDictionary.Create<string, string>());
                _secretKeyValues = Output.All(value, emptySecret).Apply(v => v[0]);
            }
        }

        [Input("secretString")]
        private Input<string>? _secretString;

        /// <summary>
        /// Secret string value (not returned on read).
        /// </summary>
        public Input<string>? SecretString
        {
            get => _secretString;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _secretString = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public SecretVersionArgs()
        {
        }
        public static new SecretVersionArgs Empty => new SecretVersionArgs();
    }

    public sealed class SecretVersionState : global::Pulumi.ResourceArgs
    {
        [Input("generateSecret")]
        public Input<Inputs.SecretVersionGenerateSecretGetArgs>? GenerateSecret { get; set; }

        [Input("organisationId")]
        public Input<string>? OrganisationId { get; set; }

        [Input("path")]
        public Input<string>? Path { get; set; }

        [Input("region")]
        public Input<string>? Region { get; set; }

        [Input("secretKeyValues")]
        private InputMap<string>? _secretKeyValues;
        public InputMap<string> SecretKeyValues
        {
            get => _secretKeyValues ?? (_secretKeyValues = new InputMap<string>());
            set
            {
                var emptySecret = Output.CreateSecret(ImmutableDictionary.Create<string, string>());
                _secretKeyValues = Output.All(value, emptySecret).Apply(v => v[0]);
            }
        }

        [Input("secretString")]
        private Input<string>? _secretString;

        /// <summary>
        /// Secret string value (not returned on read).
        /// </summary>
        public Input<string>? SecretString
        {
            get => _secretString;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _secretString = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Version number assigned by the platform.
        /// </summary>
        [Input("version")]
        public Input<int>? Version { get; set; }

        public SecretVersionState()
        {
        }
        public static new SecretVersionState Empty => new SecretVersionState();
    }
}
