// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Thalassa
{
    /// <summary>
    /// Manage access policy for a secret in Thalassa Secrets Manager
    /// 
    /// &gt; **Early access:** Secrets Manager is in early access. The API and Terraform resource schema may change in future provider releases.
    /// 
    /// See [Secrets Manager documentation](https://docs.thalassa.cloud/docs/secrets-manager/).
    /// 
    /// Updates the access policy for an existing secret via `UpdateAccessPolicy`.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Thalassa = Pulumi.Thalassa;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var dbPassword = new Thalassa.SecretAccessPolicy("db_password", new()
    ///     {
    ///         Region = "nl-01",
    ///         Path = dbPasswordThalassaSecret.Path,
    ///         Statements = new[]
    ///         {
    ///             new Thalassa.Inputs.SecretAccessPolicyStatementArgs
    ///             {
    ///                 Effect = "Allow",
    ///                 Actions = new[]
    ///                 {
    ///                     "read",
    ///                 },
    ///                 Principals = new[]
    ///                 {
    ///                     "team:platform",
    ///                 },
    ///             },
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// Import ID format: `{region}{path}` (same as `thalassa.Secret`).
    /// 
    /// !/bin/bash
    /// Example: terraform import thalassa_secret_access_policy.db_password nl-01/app/prod/db/password
    /// 
    /// ```sh
    /// $ pulumi import thalassa:index/secretAccessPolicy:SecretAccessPolicy db_password nl-01/app/prod/db/password
    /// ```
    /// </summary>
    [ThalassaResourceType("thalassa:index/secretAccessPolicy:SecretAccessPolicy")]
    public partial class SecretAccessPolicy : global::Pulumi.CustomResource
    {
        [Output("organisationId")]
        public Output<string?> OrganisationId { get; private set; } = null!;

        [Output("path")]
        public Output<string> Path { get; private set; } = null!;

        [Output("region")]
        public Output<string> Region { get; private set; } = null!;

        /// <summary>
        /// Access policy statements.
        /// </summary>
        [Output("statements")]
        public Output<ImmutableArray<Outputs.SecretAccessPolicyStatement>> Statements { get; private set; } = null!;


        /// <summary>
        /// Create a SecretAccessPolicy resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public SecretAccessPolicy(string name, SecretAccessPolicyArgs args, CustomResourceOptions? options = null)
            : base("thalassa:index/secretAccessPolicy:SecretAccessPolicy", name, args ?? new SecretAccessPolicyArgs(), MakeResourceOptions(options, ""))
        {
        }

        private SecretAccessPolicy(string name, Input<string> id, SecretAccessPolicyState? state = null, CustomResourceOptions? options = null)
            : base("thalassa:index/secretAccessPolicy:SecretAccessPolicy", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/sandervb2/pulumi-thalassa",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing SecretAccessPolicy resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static SecretAccessPolicy Get(string name, Input<string> id, SecretAccessPolicyState? state = null, CustomResourceOptions? options = null)
        {
            return new SecretAccessPolicy(name, id, state, options);
        }
    }

    public sealed class SecretAccessPolicyArgs : global::Pulumi.ResourceArgs
    {
        [Input("organisationId")]
        public Input<string>? OrganisationId { get; set; }

        [Input("path", required: true)]
        public Input<string> Path { get; set; } = null!;

        [Input("region", required: true)]
        public Input<string> Region { get; set; } = null!;

        [Input("statements", required: true)]
        private InputList<Inputs.SecretAccessPolicyStatementArgs>? _statements;

        /// <summary>
        /// Access policy statements.
        /// </summary>
        public InputList<Inputs.SecretAccessPolicyStatementArgs> Statements
        {
            get => _statements ?? (_statements = new InputList<Inputs.SecretAccessPolicyStatementArgs>());
            set => _statements = value;
        }

        public SecretAccessPolicyArgs()
        {
        }
        public static new SecretAccessPolicyArgs Empty => new SecretAccessPolicyArgs();
    }

    public sealed class SecretAccessPolicyState : global::Pulumi.ResourceArgs
    {
        [Input("organisationId")]
        public Input<string>? OrganisationId { get; set; }

        [Input("path")]
        public Input<string>? Path { get; set; }

        [Input("region")]
        public Input<string>? Region { get; set; }

        [Input("statements")]
        private InputList<Inputs.SecretAccessPolicyStatementGetArgs>? _statements;

        /// <summary>
        /// Access policy statements.
        /// </summary>
        public InputList<Inputs.SecretAccessPolicyStatementGetArgs> Statements
        {
            get => _statements ?? (_statements = new InputList<Inputs.SecretAccessPolicyStatementGetArgs>());
            set => _statements = value;
        }

        public SecretAccessPolicyState()
        {
        }
        public static new SecretAccessPolicyState Empty => new SecretAccessPolicyState();
    }
}
