// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Thalassa
{
    /// <summary>
    /// Manages egress rules for a security group using the batch API. This resource replaces all egress rules for the security group. This is an optional alternative to managing rules through the thalassa.SecurityGroup resource. Warning: Do not use both this resource and EgressRule in thalassa.SecurityGroup for the same security group, as this will cause conflicts.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Thalassa = Pulumi.Thalassa;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     // Create a VPC for the security group
    ///     var example = new Thalassa.Vpc("example", new()
    ///     {
    ///         Name = "example-vpc",
    ///         Description = "Example VPC for security group egress rules",
    ///         Region = "nl-01",
    ///         Cidrs = new[]
    ///         {
    ///             "10.0.0.0/16",
    ///         },
    ///     });
    /// 
    ///     // Create a security group
    ///     var exampleSecurityGroup = new Thalassa.SecurityGroup("example", new()
    ///     {
    ///         Name = "example-security-group",
    ///         Description = "Example security group",
    ///         VpcId = example.Id,
    ///         AllowSameGroupTraffic = false,
    ///     });
    /// 
    ///     // Create egress rules for the security group
    ///     var exampleSecurityGroupEgressRule = new Thalassa.SecurityGroupEgressRule("example", new()
    ///     {
    ///         SecurityGroupId = exampleSecurityGroup.Id,
    ///         Rules = new[]
    ///         {
    ///             new Thalassa.Inputs.SecurityGroupEgressRuleRuleArgs
    ///             {
    ///                 Name = "allow-all-outbound",
    ///                 IpVersion = "ipv4",
    ///                 Protocol = "all",
    ///                 Priority = 100,
    ///                 RemoteType = "address",
    ///                 RemoteAddress = "0.0.0.0/0",
    ///                 Policy = "allow",
    ///             },
    ///             new Thalassa.Inputs.SecurityGroupEgressRuleRuleArgs
    ///             {
    ///                 Name = "allow-https-outbound",
    ///                 IpVersion = "ipv4",
    ///                 Protocol = "tcp",
    ///                 Priority = 101,
    ///                 RemoteType = "address",
    ///                 RemoteAddress = "0.0.0.0/0",
    ///                 PortRangeMin = 443,
    ///                 PortRangeMax = 443,
    ///                 Policy = "allow",
    ///             },
    ///         },
    ///     });
    /// 
    ///     return new Dictionary&lt;string, object?&gt;
    ///     {
    ///         ["securityGroupId"] = exampleSecurityGroup.Id,
    ///     };
    /// });
    /// ```
    /// </summary>
    [ThalassaResourceType("thalassa:index/securityGroupEgressRule:SecurityGroupEgressRule")]
    public partial class SecurityGroupEgressRule : global::Pulumi.CustomResource
    {
        /// <summary>
        /// List of egress rules for the security group
        /// </summary>
        [Output("rules")]
        public Output<ImmutableArray<Outputs.SecurityGroupEgressRuleRule>> Rules { get; private set; } = null!;

        /// <summary>
        /// ID of the Security Group to manage egress rules for
        /// </summary>
        [Output("securityGroupId")]
        public Output<string> SecurityGroupId { get; private set; } = null!;


        /// <summary>
        /// Create a SecurityGroupEgressRule resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public SecurityGroupEgressRule(string name, SecurityGroupEgressRuleArgs args, CustomResourceOptions? options = null)
            : base("thalassa:index/securityGroupEgressRule:SecurityGroupEgressRule", name, args ?? new SecurityGroupEgressRuleArgs(), MakeResourceOptions(options, ""))
        {
        }

        private SecurityGroupEgressRule(string name, Input<string> id, SecurityGroupEgressRuleState? state = null, CustomResourceOptions? options = null)
            : base("thalassa:index/securityGroupEgressRule:SecurityGroupEgressRule", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/sandervb2/pulumi-thalassa",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing SecurityGroupEgressRule resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static SecurityGroupEgressRule Get(string name, Input<string> id, SecurityGroupEgressRuleState? state = null, CustomResourceOptions? options = null)
        {
            return new SecurityGroupEgressRule(name, id, state, options);
        }
    }

    public sealed class SecurityGroupEgressRuleArgs : global::Pulumi.ResourceArgs
    {
        [Input("rules")]
        private InputList<Inputs.SecurityGroupEgressRuleRuleArgs>? _rules;

        /// <summary>
        /// List of egress rules for the security group
        /// </summary>
        public InputList<Inputs.SecurityGroupEgressRuleRuleArgs> Rules
        {
            get => _rules ?? (_rules = new InputList<Inputs.SecurityGroupEgressRuleRuleArgs>());
            set => _rules = value;
        }

        /// <summary>
        /// ID of the Security Group to manage egress rules for
        /// </summary>
        [Input("securityGroupId", required: true)]
        public Input<string> SecurityGroupId { get; set; } = null!;

        public SecurityGroupEgressRuleArgs()
        {
        }
        public static new SecurityGroupEgressRuleArgs Empty => new SecurityGroupEgressRuleArgs();
    }

    public sealed class SecurityGroupEgressRuleState : global::Pulumi.ResourceArgs
    {
        [Input("rules")]
        private InputList<Inputs.SecurityGroupEgressRuleRuleGetArgs>? _rules;

        /// <summary>
        /// List of egress rules for the security group
        /// </summary>
        public InputList<Inputs.SecurityGroupEgressRuleRuleGetArgs> Rules
        {
            get => _rules ?? (_rules = new InputList<Inputs.SecurityGroupEgressRuleRuleGetArgs>());
            set => _rules = value;
        }

        /// <summary>
        /// ID of the Security Group to manage egress rules for
        /// </summary>
        [Input("securityGroupId")]
        public Input<string>? SecurityGroupId { get; set; }

        public SecurityGroupEgressRuleState()
        {
        }
        public static new SecurityGroupEgressRuleState Empty => new SecurityGroupEgressRuleState();
    }
}
