// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Thalassa
{
    /// <summary>
    /// Provides a Thalassa Cloud TFS (Thalassa Filesystem Service) instance resource.
    /// 		TFS provides a high-availability, multi-availability zone Network File System (NFS) service
    /// 		for shared storage across your infrastructure. TFS supports NFSv4 and NFSv4.1 protocols.
    /// </summary>
    [ThalassaResourceType("thalassa:index/tfsInstance:TfsInstance")]
    public partial class TfsInstance : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Annotations for the TFS instance
        /// </summary>
        [Output("annotations")]
        public Output<ImmutableDictionary<string, string>?> Annotations { get; private set; } = null!;

        /// <summary>
        /// Delete protection of the TFS instance
        /// </summary>
        [Output("deleteProtection")]
        public Output<bool?> DeleteProtection { get; private set; } = null!;

        /// <summary>
        /// A human readable description about the TFS instance
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// List of endpoints for the TFS instance
        /// </summary>
        [Output("endpoints")]
        public Output<ImmutableArray<Outputs.TfsInstanceEndpoint>> Endpoints { get; private set; } = null!;

        /// <summary>
        /// Labels for the TFS instance
        /// </summary>
        [Output("labels")]
        public Output<ImmutableDictionary<string, string>?> Labels { get; private set; } = null!;

        /// <summary>
        /// Name of the TFS instance
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Reference to the Organisation of the TFS Instance. If not provided, the organisation of the (Terraform) provider will be used.
        /// </summary>
        [Output("organisationId")]
        public Output<string?> OrganisationId { get; private set; } = null!;

        /// <summary>
        /// Region of the TFS instance
        /// </summary>
        [Output("region")]
        public Output<string> Region { get; private set; } = null!;

        /// <summary>
        /// List of security group identities to attach to the TFS instance
        /// </summary>
        [Output("securityGroupIds")]
        public Output<ImmutableArray<string>> SecurityGroupIds { get; private set; } = null!;

        /// <summary>
        /// Size of the TFS instance in GB
        /// </summary>
        [Output("sizeGb")]
        public Output<int> SizeGb { get; private set; } = null!;

        [Output("slug")]
        public Output<string> Slug { get; private set; } = null!;

        /// <summary>
        /// Status of the TFS instance
        /// </summary>
        [Output("status")]
        public Output<string> Status { get; private set; } = null!;

        /// <summary>
        /// Identity of the subnet to create the TFS instance in
        /// </summary>
        [Output("subnetId")]
        public Output<string> SubnetId { get; private set; } = null!;

        /// <summary>
        /// Identity of the VPC to create the TFS instance in
        /// </summary>
        [Output("vpcId")]
        public Output<string> VpcId { get; private set; } = null!;

        /// <summary>
        /// Wait until the TFS instance is available
        /// </summary>
        [Output("waitUntilAvailable")]
        public Output<bool?> WaitUntilAvailable { get; private set; } = null!;


        /// <summary>
        /// Create a TfsInstance resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public TfsInstance(string name, TfsInstanceArgs args, CustomResourceOptions? options = null)
            : base("thalassa:index/tfsInstance:TfsInstance", name, args ?? new TfsInstanceArgs(), MakeResourceOptions(options, ""))
        {
        }

        private TfsInstance(string name, Input<string> id, TfsInstanceState? state = null, CustomResourceOptions? options = null)
            : base("thalassa:index/tfsInstance:TfsInstance", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/sandervb2/pulumi-thalassa",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing TfsInstance resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static TfsInstance Get(string name, Input<string> id, TfsInstanceState? state = null, CustomResourceOptions? options = null)
        {
            return new TfsInstance(name, id, state, options);
        }
    }

    public sealed class TfsInstanceArgs : global::Pulumi.ResourceArgs
    {
        [Input("annotations")]
        private InputMap<string>? _annotations;

        /// <summary>
        /// Annotations for the TFS instance
        /// </summary>
        public InputMap<string> Annotations
        {
            get => _annotations ?? (_annotations = new InputMap<string>());
            set => _annotations = value;
        }

        /// <summary>
        /// Delete protection of the TFS instance
        /// </summary>
        [Input("deleteProtection")]
        public Input<bool>? DeleteProtection { get; set; }

        /// <summary>
        /// A human readable description about the TFS instance
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("labels")]
        private InputMap<string>? _labels;

        /// <summary>
        /// Labels for the TFS instance
        /// </summary>
        public InputMap<string> Labels
        {
            get => _labels ?? (_labels = new InputMap<string>());
            set => _labels = value;
        }

        /// <summary>
        /// Name of the TFS instance
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Reference to the Organisation of the TFS Instance. If not provided, the organisation of the (Terraform) provider will be used.
        /// </summary>
        [Input("organisationId")]
        public Input<string>? OrganisationId { get; set; }

        /// <summary>
        /// Region of the TFS instance
        /// </summary>
        [Input("region", required: true)]
        public Input<string> Region { get; set; } = null!;

        [Input("securityGroupIds")]
        private InputList<string>? _securityGroupIds;

        /// <summary>
        /// List of security group identities to attach to the TFS instance
        /// </summary>
        public InputList<string> SecurityGroupIds
        {
            get => _securityGroupIds ?? (_securityGroupIds = new InputList<string>());
            set => _securityGroupIds = value;
        }

        /// <summary>
        /// Size of the TFS instance in GB
        /// </summary>
        [Input("sizeGb", required: true)]
        public Input<int> SizeGb { get; set; } = null!;

        /// <summary>
        /// Identity of the subnet to create the TFS instance in
        /// </summary>
        [Input("subnetId", required: true)]
        public Input<string> SubnetId { get; set; } = null!;

        /// <summary>
        /// Identity of the VPC to create the TFS instance in
        /// </summary>
        [Input("vpcId", required: true)]
        public Input<string> VpcId { get; set; } = null!;

        /// <summary>
        /// Wait until the TFS instance is available
        /// </summary>
        [Input("waitUntilAvailable")]
        public Input<bool>? WaitUntilAvailable { get; set; }

        public TfsInstanceArgs()
        {
        }
        public static new TfsInstanceArgs Empty => new TfsInstanceArgs();
    }

    public sealed class TfsInstanceState : global::Pulumi.ResourceArgs
    {
        [Input("annotations")]
        private InputMap<string>? _annotations;

        /// <summary>
        /// Annotations for the TFS instance
        /// </summary>
        public InputMap<string> Annotations
        {
            get => _annotations ?? (_annotations = new InputMap<string>());
            set => _annotations = value;
        }

        /// <summary>
        /// Delete protection of the TFS instance
        /// </summary>
        [Input("deleteProtection")]
        public Input<bool>? DeleteProtection { get; set; }

        /// <summary>
        /// A human readable description about the TFS instance
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("endpoints")]
        private InputList<Inputs.TfsInstanceEndpointGetArgs>? _endpoints;

        /// <summary>
        /// List of endpoints for the TFS instance
        /// </summary>
        public InputList<Inputs.TfsInstanceEndpointGetArgs> Endpoints
        {
            get => _endpoints ?? (_endpoints = new InputList<Inputs.TfsInstanceEndpointGetArgs>());
            set => _endpoints = value;
        }

        [Input("labels")]
        private InputMap<string>? _labels;

        /// <summary>
        /// Labels for the TFS instance
        /// </summary>
        public InputMap<string> Labels
        {
            get => _labels ?? (_labels = new InputMap<string>());
            set => _labels = value;
        }

        /// <summary>
        /// Name of the TFS instance
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Reference to the Organisation of the TFS Instance. If not provided, the organisation of the (Terraform) provider will be used.
        /// </summary>
        [Input("organisationId")]
        public Input<string>? OrganisationId { get; set; }

        /// <summary>
        /// Region of the TFS instance
        /// </summary>
        [Input("region")]
        public Input<string>? Region { get; set; }

        [Input("securityGroupIds")]
        private InputList<string>? _securityGroupIds;

        /// <summary>
        /// List of security group identities to attach to the TFS instance
        /// </summary>
        public InputList<string> SecurityGroupIds
        {
            get => _securityGroupIds ?? (_securityGroupIds = new InputList<string>());
            set => _securityGroupIds = value;
        }

        /// <summary>
        /// Size of the TFS instance in GB
        /// </summary>
        [Input("sizeGb")]
        public Input<int>? SizeGb { get; set; }

        [Input("slug")]
        public Input<string>? Slug { get; set; }

        /// <summary>
        /// Status of the TFS instance
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        /// <summary>
        /// Identity of the subnet to create the TFS instance in
        /// </summary>
        [Input("subnetId")]
        public Input<string>? SubnetId { get; set; }

        /// <summary>
        /// Identity of the VPC to create the TFS instance in
        /// </summary>
        [Input("vpcId")]
        public Input<string>? VpcId { get; set; }

        /// <summary>
        /// Wait until the TFS instance is available
        /// </summary>
        [Input("waitUntilAvailable")]
        public Input<bool>? WaitUntilAvailable { get; set; }

        public TfsInstanceState()
        {
        }
        public static new TfsInstanceState Empty => new TfsInstanceState();
    }
}
