# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetNatgatewayResult',
    'AwaitableGetNatgatewayResult',
    'get_natgateway',
    'get_natgateway_output',
]

@pulumi.output_type
class GetNatgatewayResult:
    """
    A collection of values returned by getNatgateway.
    """
    def __init__(__self__, annotations=None, created_at=None, description=None, endpoint_ip=None, id=None, labels=None, name=None, organisation_id=None, region=None, security_group_attachments=None, slug=None, status=None, subnet_id=None, updated_at=None, v4_ip=None, v6_ip=None, vpc_id=None):
        if annotations and not isinstance(annotations, dict):
            raise TypeError("Expected argument 'annotations' to be a dict")
        pulumi.set(__self__, "annotations", annotations)
        if created_at and not isinstance(created_at, str):
            raise TypeError("Expected argument 'created_at' to be a str")
        pulumi.set(__self__, "created_at", created_at)
        if description and not isinstance(description, str):
            raise TypeError("Expected argument 'description' to be a str")
        pulumi.set(__self__, "description", description)
        if endpoint_ip and not isinstance(endpoint_ip, str):
            raise TypeError("Expected argument 'endpoint_ip' to be a str")
        pulumi.set(__self__, "endpoint_ip", endpoint_ip)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if labels and not isinstance(labels, dict):
            raise TypeError("Expected argument 'labels' to be a dict")
        pulumi.set(__self__, "labels", labels)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if organisation_id and not isinstance(organisation_id, str):
            raise TypeError("Expected argument 'organisation_id' to be a str")
        pulumi.set(__self__, "organisation_id", organisation_id)
        if region and not isinstance(region, str):
            raise TypeError("Expected argument 'region' to be a str")
        pulumi.set(__self__, "region", region)
        if security_group_attachments and not isinstance(security_group_attachments, list):
            raise TypeError("Expected argument 'security_group_attachments' to be a list")
        pulumi.set(__self__, "security_group_attachments", security_group_attachments)
        if slug and not isinstance(slug, str):
            raise TypeError("Expected argument 'slug' to be a str")
        pulumi.set(__self__, "slug", slug)
        if status and not isinstance(status, str):
            raise TypeError("Expected argument 'status' to be a str")
        pulumi.set(__self__, "status", status)
        if subnet_id and not isinstance(subnet_id, str):
            raise TypeError("Expected argument 'subnet_id' to be a str")
        pulumi.set(__self__, "subnet_id", subnet_id)
        if updated_at and not isinstance(updated_at, str):
            raise TypeError("Expected argument 'updated_at' to be a str")
        pulumi.set(__self__, "updated_at", updated_at)
        if v4_ip and not isinstance(v4_ip, str):
            raise TypeError("Expected argument 'v4_ip' to be a str")
        pulumi.set(__self__, "v4_ip", v4_ip)
        if v6_ip and not isinstance(v6_ip, str):
            raise TypeError("Expected argument 'v6_ip' to be a str")
        pulumi.set(__self__, "v6_ip", v6_ip)
        if vpc_id and not isinstance(vpc_id, str):
            raise TypeError("Expected argument 'vpc_id' to be a str")
        pulumi.set(__self__, "vpc_id", vpc_id)

    @_builtins.property
    @pulumi.getter
    def annotations(self) -> Mapping[str, _builtins.str]:
        """
        Annotations for the NAT Gateway
        """
        return pulumi.get(self, "annotations")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> _builtins.str:
        """
        The timestamp when the NAT Gateway was created
        """
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter
    def description(self) -> _builtins.str:
        """
        A human readable description about the NAT Gateway
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="endpointIp")
    def endpoint_ip(self) -> _builtins.str:
        """
        Endpoint IP of the NAT Gateway
        """
        return pulumi.get(self, "endpoint_ip")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The unique identifier of the NAT Gateway
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def labels(self) -> Optional[Mapping[str, _builtins.str]]:
        """
        Labels to filter NAT Gateways by
        """
        return pulumi.get(self, "labels")

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[_builtins.str]:
        """
        The name of the NAT Gateway to look up
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="organisationId")
    def organisation_id(self) -> Optional[_builtins.str]:
        """
        Reference to the Organisation of the NAT Gateway. If not provided, the organisation of the (Terraform) provider will be used.
        """
        return pulumi.get(self, "organisation_id")

    @_builtins.property
    @pulumi.getter
    def region(self) -> Optional[_builtins.str]:
        """
        The region of the NAT Gateway
        """
        return pulumi.get(self, "region")

    @_builtins.property
    @pulumi.getter(name="securityGroupAttachments")
    def security_group_attachments(self) -> Sequence[_builtins.str]:
        """
        List of security group IDs attached to the NAT Gateway
        """
        return pulumi.get(self, "security_group_attachments")

    @_builtins.property
    @pulumi.getter
    def slug(self) -> Optional[_builtins.str]:
        """
        The slug of the NAT Gateway to look up
        """
        return pulumi.get(self, "slug")

    @_builtins.property
    @pulumi.getter
    def status(self) -> Optional[_builtins.str]:
        """
        The status of the NAT Gateway to filter by
        """
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter(name="subnetId")
    def subnet_id(self) -> Optional[_builtins.str]:
        """
        The ID of the subnet that contains the NAT Gateway
        """
        return pulumi.get(self, "subnet_id")

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> _builtins.str:
        """
        The timestamp when the NAT Gateway was last updated
        """
        return pulumi.get(self, "updated_at")

    @_builtins.property
    @pulumi.getter(name="v4Ip")
    def v4_ip(self) -> _builtins.str:
        """
        V4 IP of the NAT Gateway
        """
        return pulumi.get(self, "v4_ip")

    @_builtins.property
    @pulumi.getter(name="v6Ip")
    def v6_ip(self) -> _builtins.str:
        """
        V6 IP of the NAT Gateway
        """
        return pulumi.get(self, "v6_ip")

    @_builtins.property
    @pulumi.getter(name="vpcId")
    def vpc_id(self) -> Optional[_builtins.str]:
        """
        The ID of the VPC that contains the NAT Gateway
        """
        return pulumi.get(self, "vpc_id")


class AwaitableGetNatgatewayResult(GetNatgatewayResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetNatgatewayResult(
            annotations=self.annotations,
            created_at=self.created_at,
            description=self.description,
            endpoint_ip=self.endpoint_ip,
            id=self.id,
            labels=self.labels,
            name=self.name,
            organisation_id=self.organisation_id,
            region=self.region,
            security_group_attachments=self.security_group_attachments,
            slug=self.slug,
            status=self.status,
            subnet_id=self.subnet_id,
            updated_at=self.updated_at,
            v4_ip=self.v4_ip,
            v6_ip=self.v6_ip,
            vpc_id=self.vpc_id)


def get_natgateway(labels: Optional[Mapping[str, _builtins.str]] = None,
                   name: Optional[_builtins.str] = None,
                   organisation_id: Optional[_builtins.str] = None,
                   region: Optional[_builtins.str] = None,
                   slug: Optional[_builtins.str] = None,
                   status: Optional[_builtins.str] = None,
                   subnet_id: Optional[_builtins.str] = None,
                   vpc_id: Optional[_builtins.str] = None,
                   opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetNatgatewayResult:
    """
    Get a NAT Gateway by name, slug, or other attributes


    :param Mapping[str, _builtins.str] labels: Labels to filter NAT Gateways by
    :param _builtins.str name: The name of the NAT Gateway to look up
    :param _builtins.str organisation_id: Reference to the Organisation of the NAT Gateway. If not provided, the organisation of the (Terraform) provider will be used.
    :param _builtins.str region: The region of the NAT Gateway
    :param _builtins.str slug: The slug of the NAT Gateway to look up
    :param _builtins.str status: The status of the NAT Gateway to filter by
    :param _builtins.str subnet_id: The ID of the subnet that contains the NAT Gateway
    :param _builtins.str vpc_id: The ID of the VPC that contains the NAT Gateway
    """
    __args__ = dict()
    __args__['labels'] = labels
    __args__['name'] = name
    __args__['organisationId'] = organisation_id
    __args__['region'] = region
    __args__['slug'] = slug
    __args__['status'] = status
    __args__['subnetId'] = subnet_id
    __args__['vpcId'] = vpc_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('thalassa:index/getNatgateway:getNatgateway', __args__, opts=opts, typ=GetNatgatewayResult).value

    return AwaitableGetNatgatewayResult(
        annotations=pulumi.get(__ret__, 'annotations'),
        created_at=pulumi.get(__ret__, 'created_at'),
        description=pulumi.get(__ret__, 'description'),
        endpoint_ip=pulumi.get(__ret__, 'endpoint_ip'),
        id=pulumi.get(__ret__, 'id'),
        labels=pulumi.get(__ret__, 'labels'),
        name=pulumi.get(__ret__, 'name'),
        organisation_id=pulumi.get(__ret__, 'organisation_id'),
        region=pulumi.get(__ret__, 'region'),
        security_group_attachments=pulumi.get(__ret__, 'security_group_attachments'),
        slug=pulumi.get(__ret__, 'slug'),
        status=pulumi.get(__ret__, 'status'),
        subnet_id=pulumi.get(__ret__, 'subnet_id'),
        updated_at=pulumi.get(__ret__, 'updated_at'),
        v4_ip=pulumi.get(__ret__, 'v4_ip'),
        v6_ip=pulumi.get(__ret__, 'v6_ip'),
        vpc_id=pulumi.get(__ret__, 'vpc_id'))
def get_natgateway_output(labels: pulumi.Input[Optional[Optional[Mapping[str, _builtins.str]]]] = None,
                          name: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                          organisation_id: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                          region: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                          slug: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                          status: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                          subnet_id: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                          vpc_id: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                          opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetNatgatewayResult]:
    """
    Get a NAT Gateway by name, slug, or other attributes


    :param Mapping[str, _builtins.str] labels: Labels to filter NAT Gateways by
    :param _builtins.str name: The name of the NAT Gateway to look up
    :param _builtins.str organisation_id: Reference to the Organisation of the NAT Gateway. If not provided, the organisation of the (Terraform) provider will be used.
    :param _builtins.str region: The region of the NAT Gateway
    :param _builtins.str slug: The slug of the NAT Gateway to look up
    :param _builtins.str status: The status of the NAT Gateway to filter by
    :param _builtins.str subnet_id: The ID of the subnet that contains the NAT Gateway
    :param _builtins.str vpc_id: The ID of the VPC that contains the NAT Gateway
    """
    __args__ = dict()
    __args__['labels'] = labels
    __args__['name'] = name
    __args__['organisationId'] = organisation_id
    __args__['region'] = region
    __args__['slug'] = slug
    __args__['status'] = status
    __args__['subnetId'] = subnet_id
    __args__['vpcId'] = vpc_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('thalassa:index/getNatgateway:getNatgateway', __args__, opts=opts, typ=GetNatgatewayResult)
    return __ret__.apply(lambda __response__: GetNatgatewayResult(
        annotations=pulumi.get(__response__, 'annotations'),
        created_at=pulumi.get(__response__, 'created_at'),
        description=pulumi.get(__response__, 'description'),
        endpoint_ip=pulumi.get(__response__, 'endpoint_ip'),
        id=pulumi.get(__response__, 'id'),
        labels=pulumi.get(__response__, 'labels'),
        name=pulumi.get(__response__, 'name'),
        organisation_id=pulumi.get(__response__, 'organisation_id'),
        region=pulumi.get(__response__, 'region'),
        security_group_attachments=pulumi.get(__response__, 'security_group_attachments'),
        slug=pulumi.get(__response__, 'slug'),
        status=pulumi.get(__response__, 'status'),
        subnet_id=pulumi.get(__response__, 'subnet_id'),
        updated_at=pulumi.get(__response__, 'updated_at'),
        v4_ip=pulumi.get(__response__, 'v4_ip'),
        v6_ip=pulumi.get(__response__, 'v6_ip'),
        vpc_id=pulumi.get(__response__, 'vpc_id')))
