# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['SecurityGroupEgressRuleInitArgs', 'SecurityGroupEgressRule']

@pulumi.input_type
class SecurityGroupEgressRuleInitArgs:
    def __init__(__self__, *,
                 security_group_id: pulumi.Input[_builtins.str],
                 rules: pulumi.Input[Optional[Sequence[pulumi.Input['SecurityGroupEgressRuleRuleArgs']]]] = None):
        """
        The set of arguments for constructing a SecurityGroupEgressRule resource.

        :param pulumi.Input[_builtins.str] security_group_id: ID of the Security Group to manage egress rules for
        :param pulumi.Input[Sequence[pulumi.Input['SecurityGroupEgressRuleRuleArgs']]] rules: List of egress rules for the security group
        """
        pulumi.set(__self__, "security_group_id", security_group_id)
        if rules is not None:
            pulumi.set(__self__, "rules", rules)

    @_builtins.property
    @pulumi.getter(name="securityGroupId")
    def security_group_id(self) -> pulumi.Input[_builtins.str]:
        """
        ID of the Security Group to manage egress rules for
        """
        return pulumi.get(self, "security_group_id")

    @security_group_id.setter
    def security_group_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "security_group_id", value)

    @_builtins.property
    @pulumi.getter
    def rules(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['SecurityGroupEgressRuleRuleArgs']]]]:
        """
        List of egress rules for the security group
        """
        return pulumi.get(self, "rules")

    @rules.setter
    def rules(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['SecurityGroupEgressRuleRuleArgs']]]]):
        pulumi.set(self, "rules", value)


@pulumi.input_type
class _SecurityGroupEgressRuleState:
    def __init__(__self__, *,
                 rules: pulumi.Input[Optional[Sequence[pulumi.Input['SecurityGroupEgressRuleRuleArgs']]]] = None,
                 security_group_id: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering SecurityGroupEgressRule resources.

        :param pulumi.Input[Sequence[pulumi.Input['SecurityGroupEgressRuleRuleArgs']]] rules: List of egress rules for the security group
        :param pulumi.Input[_builtins.str] security_group_id: ID of the Security Group to manage egress rules for
        """
        if rules is not None:
            pulumi.set(__self__, "rules", rules)
        if security_group_id is not None:
            pulumi.set(__self__, "security_group_id", security_group_id)

    @_builtins.property
    @pulumi.getter
    def rules(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['SecurityGroupEgressRuleRuleArgs']]]]:
        """
        List of egress rules for the security group
        """
        return pulumi.get(self, "rules")

    @rules.setter
    def rules(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['SecurityGroupEgressRuleRuleArgs']]]]):
        pulumi.set(self, "rules", value)

    @_builtins.property
    @pulumi.getter(name="securityGroupId")
    def security_group_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        ID of the Security Group to manage egress rules for
        """
        return pulumi.get(self, "security_group_id")

    @security_group_id.setter
    def security_group_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "security_group_id", value)


@pulumi.type_token("thalassa:index/securityGroupEgressRule:SecurityGroupEgressRule")
class SecurityGroupEgressRule(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 rules: pulumi.Input[Optional[Sequence[pulumi.Input[Union['SecurityGroupEgressRuleRuleArgs', 'SecurityGroupEgressRuleRuleArgsDict']]]]] = None,
                 security_group_id: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Manages egress rules for a security group using the batch API. This resource replaces all egress rules for the security group. This is an optional alternative to managing rules through the SecurityGroup resource. Warning: Do not use both this resource and egress_rule in SecurityGroup for the same security group, as this will cause conflicts.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_thalassa as thalassa

        # Create a VPC for the security group
        example = thalassa.Vpc("example",
            name="example-vpc",
            description="Example VPC for security group egress rules",
            region="nl-01",
            cidrs=["10.0.0.0/16"])
        # Create a security group
        example_security_group = thalassa.SecurityGroup("example",
            name="example-security-group",
            description="Example security group",
            vpc_id=example.id,
            allow_same_group_traffic=False)
        # Create egress rules for the security group
        example_security_group_egress_rule = thalassa.SecurityGroupEgressRule("example",
            security_group_id=example_security_group.id,
            rules=[
                {
                    "name": "allow-all-outbound",
                    "ip_version": "ipv4",
                    "protocol": "all",
                    "priority": 100,
                    "remote_type": "address",
                    "remote_address": "0.0.0.0/0",
                    "policy": "allow",
                },
                {
                    "name": "allow-https-outbound",
                    "ip_version": "ipv4",
                    "protocol": "tcp",
                    "priority": 101,
                    "remote_type": "address",
                    "remote_address": "0.0.0.0/0",
                    "port_range_min": 443,
                    "port_range_max": 443,
                    "policy": "allow",
                },
            ])
        pulumi.export("securityGroupId", example_security_group.id)
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[Union['SecurityGroupEgressRuleRuleArgs', 'SecurityGroupEgressRuleRuleArgsDict']]]] rules: List of egress rules for the security group
        :param pulumi.Input[_builtins.str] security_group_id: ID of the Security Group to manage egress rules for
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: SecurityGroupEgressRuleInitArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Manages egress rules for a security group using the batch API. This resource replaces all egress rules for the security group. This is an optional alternative to managing rules through the SecurityGroup resource. Warning: Do not use both this resource and egress_rule in SecurityGroup for the same security group, as this will cause conflicts.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_thalassa as thalassa

        # Create a VPC for the security group
        example = thalassa.Vpc("example",
            name="example-vpc",
            description="Example VPC for security group egress rules",
            region="nl-01",
            cidrs=["10.0.0.0/16"])
        # Create a security group
        example_security_group = thalassa.SecurityGroup("example",
            name="example-security-group",
            description="Example security group",
            vpc_id=example.id,
            allow_same_group_traffic=False)
        # Create egress rules for the security group
        example_security_group_egress_rule = thalassa.SecurityGroupEgressRule("example",
            security_group_id=example_security_group.id,
            rules=[
                {
                    "name": "allow-all-outbound",
                    "ip_version": "ipv4",
                    "protocol": "all",
                    "priority": 100,
                    "remote_type": "address",
                    "remote_address": "0.0.0.0/0",
                    "policy": "allow",
                },
                {
                    "name": "allow-https-outbound",
                    "ip_version": "ipv4",
                    "protocol": "tcp",
                    "priority": 101,
                    "remote_type": "address",
                    "remote_address": "0.0.0.0/0",
                    "port_range_min": 443,
                    "port_range_max": 443,
                    "policy": "allow",
                },
            ])
        pulumi.export("securityGroupId", example_security_group.id)
        ```


        :param str resource_name: The name of the resource.
        :param SecurityGroupEgressRuleInitArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(SecurityGroupEgressRuleInitArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 rules: pulumi.Input[Optional[Sequence[pulumi.Input[Union['SecurityGroupEgressRuleRuleArgs', 'SecurityGroupEgressRuleRuleArgsDict']]]]] = None,
                 security_group_id: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = SecurityGroupEgressRuleInitArgs.__new__(SecurityGroupEgressRuleInitArgs)

            __props__.__dict__["rules"] = rules
            if security_group_id is None and not opts.urn:
                raise TypeError("Missing required property 'security_group_id'")
            __props__.__dict__["security_group_id"] = security_group_id
        super(SecurityGroupEgressRule, __self__).__init__(
            'thalassa:index/securityGroupEgressRule:SecurityGroupEgressRule',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            rules: pulumi.Input[Optional[Sequence[pulumi.Input[Union['SecurityGroupEgressRuleRuleArgs', 'SecurityGroupEgressRuleRuleArgsDict']]]]] = None,
            security_group_id: pulumi.Input[Optional[_builtins.str]] = None) -> 'SecurityGroupEgressRule':
        """
        Get an existing SecurityGroupEgressRule resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[Union['SecurityGroupEgressRuleRuleArgs', 'SecurityGroupEgressRuleRuleArgsDict']]]] rules: List of egress rules for the security group
        :param pulumi.Input[_builtins.str] security_group_id: ID of the Security Group to manage egress rules for
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _SecurityGroupEgressRuleState.__new__(_SecurityGroupEgressRuleState)

        __props__.__dict__["rules"] = rules
        __props__.__dict__["security_group_id"] = security_group_id
        return SecurityGroupEgressRule(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def rules(self) -> pulumi.Output[Optional[Sequence['outputs.SecurityGroupEgressRuleRule']]]:
        """
        List of egress rules for the security group
        """
        return pulumi.get(self, "rules")

    @_builtins.property
    @pulumi.getter(name="securityGroupId")
    def security_group_id(self) -> pulumi.Output[_builtins.str]:
        """
        ID of the Security Group to manage egress rules for
        """
        return pulumi.get(self, "security_group_id")

