# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['SnapshotArgs', 'Snapshot']

@pulumi.input_type
class SnapshotArgs:
    def __init__(__self__, *,
                 annotations: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 delete_protection: pulumi.Input[Optional[_builtins.bool]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 labels: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 organisation_id: pulumi.Input[Optional[_builtins.str]] = None,
                 wait_until_available: pulumi.Input[Optional[_builtins.bool]] = None):
        """
        The set of arguments for constructing a Snapshot resource.

        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] annotations: Annotations for the snapshot
        :param pulumi.Input[_builtins.bool] delete_protection: Delete protection of the snapshot
        :param pulumi.Input[_builtins.str] description: A human readable description about the snapshot
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels: Labels for the snapshot
        :param pulumi.Input[_builtins.str] name: Name of the snapshot
        :param pulumi.Input[_builtins.str] organisation_id: Reference to the Organisation of the Snapshot. If not provided, the organisation of the (Terraform) provider will be used.
        :param pulumi.Input[_builtins.bool] wait_until_available: Wait until the snapshot is available
        """
        if annotations is not None:
            pulumi.set(__self__, "annotations", annotations)
        if delete_protection is not None:
            pulumi.set(__self__, "delete_protection", delete_protection)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if labels is not None:
            pulumi.set(__self__, "labels", labels)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if organisation_id is not None:
            pulumi.set(__self__, "organisation_id", organisation_id)
        if wait_until_available is not None:
            pulumi.set(__self__, "wait_until_available", wait_until_available)

    @_builtins.property
    @pulumi.getter
    def annotations(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Annotations for the snapshot
        """
        return pulumi.get(self, "annotations")

    @annotations.setter
    def annotations(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "annotations", value)

    @_builtins.property
    @pulumi.getter(name="deleteProtection")
    def delete_protection(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Delete protection of the snapshot
        """
        return pulumi.get(self, "delete_protection")

    @delete_protection.setter
    def delete_protection(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "delete_protection", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        A human readable description about the snapshot
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def labels(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Labels for the snapshot
        """
        return pulumi.get(self, "labels")

    @labels.setter
    def labels(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "labels", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Name of the snapshot
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="organisationId")
    def organisation_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Reference to the Organisation of the Snapshot. If not provided, the organisation of the (Terraform) provider will be used.
        """
        return pulumi.get(self, "organisation_id")

    @organisation_id.setter
    def organisation_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "organisation_id", value)

    @_builtins.property
    @pulumi.getter(name="waitUntilAvailable")
    def wait_until_available(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Wait until the snapshot is available
        """
        return pulumi.get(self, "wait_until_available")

    @wait_until_available.setter
    def wait_until_available(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "wait_until_available", value)


@pulumi.input_type
class _SnapshotState:
    def __init__(__self__, *,
                 annotations: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 delete_protection: pulumi.Input[Optional[_builtins.bool]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 labels: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 organisation_id: pulumi.Input[Optional[_builtins.str]] = None,
                 region: pulumi.Input[Optional[_builtins.str]] = None,
                 size_gb: pulumi.Input[Optional[_builtins.int]] = None,
                 slug: pulumi.Input[Optional[_builtins.str]] = None,
                 snapshot_policy_id: pulumi.Input[Optional[_builtins.str]] = None,
                 source_volume_id: pulumi.Input[Optional[_builtins.str]] = None,
                 status: pulumi.Input[Optional[_builtins.str]] = None,
                 wait_until_available: pulumi.Input[Optional[_builtins.bool]] = None):
        """
        Input properties used for looking up and filtering Snapshot resources.

        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] annotations: Annotations for the snapshot
        :param pulumi.Input[_builtins.bool] delete_protection: Delete protection of the snapshot
        :param pulumi.Input[_builtins.str] description: A human readable description about the snapshot
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels: Labels for the snapshot
        :param pulumi.Input[_builtins.str] name: Name of the snapshot
        :param pulumi.Input[_builtins.str] organisation_id: Reference to the Organisation of the Snapshot. If not provided, the organisation of the (Terraform) provider will be used.
        :param pulumi.Input[_builtins.str] region: Region of the snapshot
        :param pulumi.Input[_builtins.int] size_gb: Size of the snapshot in GB
        :param pulumi.Input[_builtins.str] snapshot_policy_id: Identity of the snapshot policy that created this snapshot
        :param pulumi.Input[_builtins.str] source_volume_id: Identity of the source volume
        :param pulumi.Input[_builtins.str] status: Status of the snapshot
        :param pulumi.Input[_builtins.bool] wait_until_available: Wait until the snapshot is available
        """
        if annotations is not None:
            pulumi.set(__self__, "annotations", annotations)
        if delete_protection is not None:
            pulumi.set(__self__, "delete_protection", delete_protection)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if labels is not None:
            pulumi.set(__self__, "labels", labels)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if organisation_id is not None:
            pulumi.set(__self__, "organisation_id", organisation_id)
        if region is not None:
            pulumi.set(__self__, "region", region)
        if size_gb is not None:
            pulumi.set(__self__, "size_gb", size_gb)
        if slug is not None:
            pulumi.set(__self__, "slug", slug)
        if snapshot_policy_id is not None:
            pulumi.set(__self__, "snapshot_policy_id", snapshot_policy_id)
        if source_volume_id is not None:
            pulumi.set(__self__, "source_volume_id", source_volume_id)
        if status is not None:
            pulumi.set(__self__, "status", status)
        if wait_until_available is not None:
            pulumi.set(__self__, "wait_until_available", wait_until_available)

    @_builtins.property
    @pulumi.getter
    def annotations(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Annotations for the snapshot
        """
        return pulumi.get(self, "annotations")

    @annotations.setter
    def annotations(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "annotations", value)

    @_builtins.property
    @pulumi.getter(name="deleteProtection")
    def delete_protection(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Delete protection of the snapshot
        """
        return pulumi.get(self, "delete_protection")

    @delete_protection.setter
    def delete_protection(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "delete_protection", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        A human readable description about the snapshot
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def labels(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Labels for the snapshot
        """
        return pulumi.get(self, "labels")

    @labels.setter
    def labels(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "labels", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Name of the snapshot
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="organisationId")
    def organisation_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Reference to the Organisation of the Snapshot. If not provided, the organisation of the (Terraform) provider will be used.
        """
        return pulumi.get(self, "organisation_id")

    @organisation_id.setter
    def organisation_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "organisation_id", value)

    @_builtins.property
    @pulumi.getter
    def region(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Region of the snapshot
        """
        return pulumi.get(self, "region")

    @region.setter
    def region(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "region", value)

    @_builtins.property
    @pulumi.getter(name="sizeGb")
    def size_gb(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Size of the snapshot in GB
        """
        return pulumi.get(self, "size_gb")

    @size_gb.setter
    def size_gb(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "size_gb", value)

    @_builtins.property
    @pulumi.getter
    def slug(self) -> pulumi.Input[Optional[_builtins.str]]:
        return pulumi.get(self, "slug")

    @slug.setter
    def slug(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "slug", value)

    @_builtins.property
    @pulumi.getter(name="snapshotPolicyId")
    def snapshot_policy_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Identity of the snapshot policy that created this snapshot
        """
        return pulumi.get(self, "snapshot_policy_id")

    @snapshot_policy_id.setter
    def snapshot_policy_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "snapshot_policy_id", value)

    @_builtins.property
    @pulumi.getter(name="sourceVolumeId")
    def source_volume_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Identity of the source volume
        """
        return pulumi.get(self, "source_volume_id")

    @source_volume_id.setter
    def source_volume_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "source_volume_id", value)

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Status of the snapshot
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "status", value)

    @_builtins.property
    @pulumi.getter(name="waitUntilAvailable")
    def wait_until_available(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Wait until the snapshot is available
        """
        return pulumi.get(self, "wait_until_available")

    @wait_until_available.setter
    def wait_until_available(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "wait_until_available", value)


@pulumi.type_token("thalassa:index/snapshot:Snapshot")
class Snapshot(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 annotations: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 delete_protection: pulumi.Input[Optional[_builtins.bool]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 labels: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 organisation_id: pulumi.Input[Optional[_builtins.str]] = None,
                 wait_until_available: pulumi.Input[Optional[_builtins.bool]] = None,
                 __props__=None):
        """
        Provides a Thalassa Cloud Snapshot resource. This can be used to create, manage, and delete snapshots of block volumes.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_thalassa as thalassa

        # Create a block volume to snapshot
        example = thalassa.BlockVolume("example",
            name="example-block-volume",
            description="Example block volume for snapshot",
            region="nl-01",
            volume_type="Block",
            size_gb=20)
        # Create a snapshot from the block volume
        example_snapshot = thalassa.Snapshot("example",
            name="example-snapshot",
            description="Example snapshot created from block volume",
            delete_protection=False,
            wait_until_available=True,
            labels={
                "environment": "production",
                "backup": "daily",
                "service": "database",
            },
            annotations={
                "cost-center": "cc-12345",
                "retention": "30d",
            })
        pulumi.export("snapshotId", example_snapshot.id)
        pulumi.export("snapshotName", example_snapshot.name)
        pulumi.export("snapshotStatus", example_snapshot.status)
        pulumi.export("snapshotSizeGb", example_snapshot.size_gb)
        pulumi.export("sourceVolumeId", example_snapshot.source_volume_id)
        ```


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] annotations: Annotations for the snapshot
        :param pulumi.Input[_builtins.bool] delete_protection: Delete protection of the snapshot
        :param pulumi.Input[_builtins.str] description: A human readable description about the snapshot
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels: Labels for the snapshot
        :param pulumi.Input[_builtins.str] name: Name of the snapshot
        :param pulumi.Input[_builtins.str] organisation_id: Reference to the Organisation of the Snapshot. If not provided, the organisation of the (Terraform) provider will be used.
        :param pulumi.Input[_builtins.bool] wait_until_available: Wait until the snapshot is available
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[SnapshotArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Provides a Thalassa Cloud Snapshot resource. This can be used to create, manage, and delete snapshots of block volumes.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_thalassa as thalassa

        # Create a block volume to snapshot
        example = thalassa.BlockVolume("example",
            name="example-block-volume",
            description="Example block volume for snapshot",
            region="nl-01",
            volume_type="Block",
            size_gb=20)
        # Create a snapshot from the block volume
        example_snapshot = thalassa.Snapshot("example",
            name="example-snapshot",
            description="Example snapshot created from block volume",
            delete_protection=False,
            wait_until_available=True,
            labels={
                "environment": "production",
                "backup": "daily",
                "service": "database",
            },
            annotations={
                "cost-center": "cc-12345",
                "retention": "30d",
            })
        pulumi.export("snapshotId", example_snapshot.id)
        pulumi.export("snapshotName", example_snapshot.name)
        pulumi.export("snapshotStatus", example_snapshot.status)
        pulumi.export("snapshotSizeGb", example_snapshot.size_gb)
        pulumi.export("sourceVolumeId", example_snapshot.source_volume_id)
        ```


        :param str resource_name: The name of the resource.
        :param SnapshotArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(SnapshotArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 annotations: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 delete_protection: pulumi.Input[Optional[_builtins.bool]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 labels: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 organisation_id: pulumi.Input[Optional[_builtins.str]] = None,
                 wait_until_available: pulumi.Input[Optional[_builtins.bool]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = SnapshotArgs.__new__(SnapshotArgs)

            __props__.__dict__["annotations"] = annotations
            __props__.__dict__["delete_protection"] = delete_protection
            __props__.__dict__["description"] = description
            __props__.__dict__["labels"] = labels
            __props__.__dict__["name"] = name
            __props__.__dict__["organisation_id"] = organisation_id
            __props__.__dict__["wait_until_available"] = wait_until_available
            __props__.__dict__["region"] = None
            __props__.__dict__["size_gb"] = None
            __props__.__dict__["slug"] = None
            __props__.__dict__["snapshot_policy_id"] = None
            __props__.__dict__["source_volume_id"] = None
            __props__.__dict__["status"] = None
        super(Snapshot, __self__).__init__(
            'thalassa:index/snapshot:Snapshot',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            annotations: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
            delete_protection: pulumi.Input[Optional[_builtins.bool]] = None,
            description: pulumi.Input[Optional[_builtins.str]] = None,
            labels: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            organisation_id: pulumi.Input[Optional[_builtins.str]] = None,
            region: pulumi.Input[Optional[_builtins.str]] = None,
            size_gb: pulumi.Input[Optional[_builtins.int]] = None,
            slug: pulumi.Input[Optional[_builtins.str]] = None,
            snapshot_policy_id: pulumi.Input[Optional[_builtins.str]] = None,
            source_volume_id: pulumi.Input[Optional[_builtins.str]] = None,
            status: pulumi.Input[Optional[_builtins.str]] = None,
            wait_until_available: pulumi.Input[Optional[_builtins.bool]] = None) -> 'Snapshot':
        """
        Get an existing Snapshot resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] annotations: Annotations for the snapshot
        :param pulumi.Input[_builtins.bool] delete_protection: Delete protection of the snapshot
        :param pulumi.Input[_builtins.str] description: A human readable description about the snapshot
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] labels: Labels for the snapshot
        :param pulumi.Input[_builtins.str] name: Name of the snapshot
        :param pulumi.Input[_builtins.str] organisation_id: Reference to the Organisation of the Snapshot. If not provided, the organisation of the (Terraform) provider will be used.
        :param pulumi.Input[_builtins.str] region: Region of the snapshot
        :param pulumi.Input[_builtins.int] size_gb: Size of the snapshot in GB
        :param pulumi.Input[_builtins.str] snapshot_policy_id: Identity of the snapshot policy that created this snapshot
        :param pulumi.Input[_builtins.str] source_volume_id: Identity of the source volume
        :param pulumi.Input[_builtins.str] status: Status of the snapshot
        :param pulumi.Input[_builtins.bool] wait_until_available: Wait until the snapshot is available
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _SnapshotState.__new__(_SnapshotState)

        __props__.__dict__["annotations"] = annotations
        __props__.__dict__["delete_protection"] = delete_protection
        __props__.__dict__["description"] = description
        __props__.__dict__["labels"] = labels
        __props__.__dict__["name"] = name
        __props__.__dict__["organisation_id"] = organisation_id
        __props__.__dict__["region"] = region
        __props__.__dict__["size_gb"] = size_gb
        __props__.__dict__["slug"] = slug
        __props__.__dict__["snapshot_policy_id"] = snapshot_policy_id
        __props__.__dict__["source_volume_id"] = source_volume_id
        __props__.__dict__["status"] = status
        __props__.__dict__["wait_until_available"] = wait_until_available
        return Snapshot(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def annotations(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        """
        Annotations for the snapshot
        """
        return pulumi.get(self, "annotations")

    @_builtins.property
    @pulumi.getter(name="deleteProtection")
    def delete_protection(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Delete protection of the snapshot
        """
        return pulumi.get(self, "delete_protection")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        A human readable description about the snapshot
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def labels(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        """
        Labels for the snapshot
        """
        return pulumi.get(self, "labels")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Name of the snapshot
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="organisationId")
    def organisation_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Reference to the Organisation of the Snapshot. If not provided, the organisation of the (Terraform) provider will be used.
        """
        return pulumi.get(self, "organisation_id")

    @_builtins.property
    @pulumi.getter
    def region(self) -> pulumi.Output[_builtins.str]:
        """
        Region of the snapshot
        """
        return pulumi.get(self, "region")

    @_builtins.property
    @pulumi.getter(name="sizeGb")
    def size_gb(self) -> pulumi.Output[_builtins.int]:
        """
        Size of the snapshot in GB
        """
        return pulumi.get(self, "size_gb")

    @_builtins.property
    @pulumi.getter
    def slug(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "slug")

    @_builtins.property
    @pulumi.getter(name="snapshotPolicyId")
    def snapshot_policy_id(self) -> pulumi.Output[_builtins.str]:
        """
        Identity of the snapshot policy that created this snapshot
        """
        return pulumi.get(self, "snapshot_policy_id")

    @_builtins.property
    @pulumi.getter(name="sourceVolumeId")
    def source_volume_id(self) -> pulumi.Output[_builtins.str]:
        """
        Identity of the source volume
        """
        return pulumi.get(self, "source_volume_id")

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Output[_builtins.str]:
        """
        Status of the snapshot
        """
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter(name="waitUntilAvailable")
    def wait_until_available(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Wait until the snapshot is available
        """
        return pulumi.get(self, "wait_until_available")

