// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package thalassa

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/sandervb2/pulumi-thalassa/sdk/go/thalassa/internal"
)

// Manage a secret version in Thalassa Secrets Manager
//
// > **Early access:** Secrets Manager is in early access. The API and Terraform resource schema may change in future provider releases.
//
// See [Secrets Manager documentation](https://docs.thalassa.cloud/docs/secrets-manager/).
//
// Stores a new secret version via `PutSecretValue`. Plaintext is not returned on read.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/sandervb2/pulumi-thalassa/sdk/go/thalassa"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := thalassa.NewSecretVersion(ctx, "db_password", &thalassa.SecretVersionArgs{
//				Region:       pulumi.String("nl-01"),
//				Path:         pulumi.Any(dbPasswordThalassaSecret.Path),
//				SecretString: pulumi.String("initial-password"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Import
//
// Import ID format: `{region}{path}/{version}` (e.g. `nl-01/app/prod/db/password/3`).
//
// !/bin/bash
// Example: terraform import thalassa_secret_version.db_password nl-01/app/prod/db/password/3
//
// ```sh
// $ pulumi import thalassa:index/secretVersion:SecretVersion db_password nl-01/app/prod/db/password/3
// ```
type SecretVersion struct {
	pulumi.CustomResourceState

	GenerateSecret  SecretVersionGenerateSecretPtrOutput `pulumi:"generateSecret"`
	OrganisationId  pulumi.StringPtrOutput               `pulumi:"organisationId"`
	Path            pulumi.StringOutput                  `pulumi:"path"`
	Region          pulumi.StringOutput                  `pulumi:"region"`
	SecretKeyValues pulumi.StringMapOutput               `pulumi:"secretKeyValues"`
	// Secret string value (not returned on read).
	SecretString pulumi.StringPtrOutput `pulumi:"secretString"`
	// Version number assigned by the platform.
	Version pulumi.IntOutput `pulumi:"version"`
}

// NewSecretVersion registers a new resource with the given unique name, arguments, and options.
func NewSecretVersion(ctx *pulumi.Context,
	name string, args *SecretVersionArgs, opts ...pulumi.ResourceOption) (*SecretVersion, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Path == nil {
		return nil, errors.New("invalid value for required argument 'Path'")
	}
	if args.Region == nil {
		return nil, errors.New("invalid value for required argument 'Region'")
	}
	if args.SecretKeyValues != nil {
		args.SecretKeyValues = pulumi.ToSecret(args.SecretKeyValues).(pulumi.StringMapInput)
	}
	if args.SecretString != nil {
		args.SecretString = pulumi.ToSecret(args.SecretString).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"secretKeyValues",
		"secretString",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource SecretVersion
	err := ctx.RegisterResource("thalassa:index/secretVersion:SecretVersion", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSecretVersion gets an existing SecretVersion resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSecretVersion(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SecretVersionState, opts ...pulumi.ResourceOption) (*SecretVersion, error) {
	var resource SecretVersion
	err := ctx.ReadResource("thalassa:index/secretVersion:SecretVersion", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SecretVersion resources.
type secretVersionState struct {
	GenerateSecret  *SecretVersionGenerateSecret `pulumi:"generateSecret"`
	OrganisationId  *string                      `pulumi:"organisationId"`
	Path            *string                      `pulumi:"path"`
	Region          *string                      `pulumi:"region"`
	SecretKeyValues map[string]string            `pulumi:"secretKeyValues"`
	// Secret string value (not returned on read).
	SecretString *string `pulumi:"secretString"`
	// Version number assigned by the platform.
	Version *int `pulumi:"version"`
}

type SecretVersionState struct {
	GenerateSecret  SecretVersionGenerateSecretPtrInput
	OrganisationId  pulumi.StringPtrInput
	Path            pulumi.StringPtrInput
	Region          pulumi.StringPtrInput
	SecretKeyValues pulumi.StringMapInput
	// Secret string value (not returned on read).
	SecretString pulumi.StringPtrInput
	// Version number assigned by the platform.
	Version pulumi.IntPtrInput
}

func (SecretVersionState) ElementType() reflect.Type {
	return reflect.TypeOf((*secretVersionState)(nil)).Elem()
}

type secretVersionArgs struct {
	GenerateSecret  *SecretVersionGenerateSecret `pulumi:"generateSecret"`
	OrganisationId  *string                      `pulumi:"organisationId"`
	Path            string                       `pulumi:"path"`
	Region          string                       `pulumi:"region"`
	SecretKeyValues map[string]string            `pulumi:"secretKeyValues"`
	// Secret string value (not returned on read).
	SecretString *string `pulumi:"secretString"`
}

// The set of arguments for constructing a SecretVersion resource.
type SecretVersionArgs struct {
	GenerateSecret  SecretVersionGenerateSecretPtrInput
	OrganisationId  pulumi.StringPtrInput
	Path            pulumi.StringInput
	Region          pulumi.StringInput
	SecretKeyValues pulumi.StringMapInput
	// Secret string value (not returned on read).
	SecretString pulumi.StringPtrInput
}

func (SecretVersionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*secretVersionArgs)(nil)).Elem()
}

type SecretVersionInput interface {
	pulumi.Input

	ToSecretVersionOutput() SecretVersionOutput
	ToSecretVersionOutputWithContext(ctx context.Context) SecretVersionOutput
}

func (*SecretVersion) ElementType() reflect.Type {
	return reflect.TypeOf((**SecretVersion)(nil)).Elem()
}

func (i *SecretVersion) ToSecretVersionOutput() SecretVersionOutput {
	return i.ToSecretVersionOutputWithContext(context.Background())
}

func (i *SecretVersion) ToSecretVersionOutputWithContext(ctx context.Context) SecretVersionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SecretVersionOutput)
}

// SecretVersionArrayInput is an input type that accepts SecretVersionArray and SecretVersionArrayOutput values.
// You can construct a concrete instance of `SecretVersionArrayInput` via:
//
//	SecretVersionArray{ SecretVersionArgs{...} }
type SecretVersionArrayInput interface {
	pulumi.Input

	ToSecretVersionArrayOutput() SecretVersionArrayOutput
	ToSecretVersionArrayOutputWithContext(context.Context) SecretVersionArrayOutput
}

type SecretVersionArray []SecretVersionInput

func (SecretVersionArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SecretVersion)(nil)).Elem()
}

func (i SecretVersionArray) ToSecretVersionArrayOutput() SecretVersionArrayOutput {
	return i.ToSecretVersionArrayOutputWithContext(context.Background())
}

func (i SecretVersionArray) ToSecretVersionArrayOutputWithContext(ctx context.Context) SecretVersionArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SecretVersionArrayOutput)
}

// SecretVersionMapInput is an input type that accepts SecretVersionMap and SecretVersionMapOutput values.
// You can construct a concrete instance of `SecretVersionMapInput` via:
//
//	SecretVersionMap{ "key": SecretVersionArgs{...} }
type SecretVersionMapInput interface {
	pulumi.Input

	ToSecretVersionMapOutput() SecretVersionMapOutput
	ToSecretVersionMapOutputWithContext(context.Context) SecretVersionMapOutput
}

type SecretVersionMap map[string]SecretVersionInput

func (SecretVersionMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SecretVersion)(nil)).Elem()
}

func (i SecretVersionMap) ToSecretVersionMapOutput() SecretVersionMapOutput {
	return i.ToSecretVersionMapOutputWithContext(context.Background())
}

func (i SecretVersionMap) ToSecretVersionMapOutputWithContext(ctx context.Context) SecretVersionMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SecretVersionMapOutput)
}

type SecretVersionOutput struct{ *pulumi.OutputState }

func (SecretVersionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SecretVersion)(nil)).Elem()
}

func (o SecretVersionOutput) ToSecretVersionOutput() SecretVersionOutput {
	return o
}

func (o SecretVersionOutput) ToSecretVersionOutputWithContext(ctx context.Context) SecretVersionOutput {
	return o
}

func (o SecretVersionOutput) GenerateSecret() SecretVersionGenerateSecretPtrOutput {
	return o.ApplyT(func(v *SecretVersion) SecretVersionGenerateSecretPtrOutput { return v.GenerateSecret }).(SecretVersionGenerateSecretPtrOutput)
}

func (o SecretVersionOutput) OrganisationId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SecretVersion) pulumi.StringPtrOutput { return v.OrganisationId }).(pulumi.StringPtrOutput)
}

func (o SecretVersionOutput) Path() pulumi.StringOutput {
	return o.ApplyT(func(v *SecretVersion) pulumi.StringOutput { return v.Path }).(pulumi.StringOutput)
}

func (o SecretVersionOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v *SecretVersion) pulumi.StringOutput { return v.Region }).(pulumi.StringOutput)
}

func (o SecretVersionOutput) SecretKeyValues() pulumi.StringMapOutput {
	return o.ApplyT(func(v *SecretVersion) pulumi.StringMapOutput { return v.SecretKeyValues }).(pulumi.StringMapOutput)
}

// Secret string value (not returned on read).
func (o SecretVersionOutput) SecretString() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SecretVersion) pulumi.StringPtrOutput { return v.SecretString }).(pulumi.StringPtrOutput)
}

// Version number assigned by the platform.
func (o SecretVersionOutput) Version() pulumi.IntOutput {
	return o.ApplyT(func(v *SecretVersion) pulumi.IntOutput { return v.Version }).(pulumi.IntOutput)
}

type SecretVersionArrayOutput struct{ *pulumi.OutputState }

func (SecretVersionArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SecretVersion)(nil)).Elem()
}

func (o SecretVersionArrayOutput) ToSecretVersionArrayOutput() SecretVersionArrayOutput {
	return o
}

func (o SecretVersionArrayOutput) ToSecretVersionArrayOutputWithContext(ctx context.Context) SecretVersionArrayOutput {
	return o
}

func (o SecretVersionArrayOutput) Index(i pulumi.IntInput) SecretVersionOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *SecretVersion {
		return vs[0].([]*SecretVersion)[vs[1].(int)]
	}).(SecretVersionOutput)
}

type SecretVersionMapOutput struct{ *pulumi.OutputState }

func (SecretVersionMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SecretVersion)(nil)).Elem()
}

func (o SecretVersionMapOutput) ToSecretVersionMapOutput() SecretVersionMapOutput {
	return o
}

func (o SecretVersionMapOutput) ToSecretVersionMapOutputWithContext(ctx context.Context) SecretVersionMapOutput {
	return o
}

func (o SecretVersionMapOutput) MapIndex(k pulumi.StringInput) SecretVersionOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *SecretVersion {
		return vs[0].(map[string]*SecretVersion)[vs[1].(string)]
	}).(SecretVersionOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SecretVersionInput)(nil)).Elem(), &SecretVersion{})
	pulumi.RegisterInputType(reflect.TypeOf((*SecretVersionArrayInput)(nil)).Elem(), SecretVersionArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*SecretVersionMapInput)(nil)).Elem(), SecretVersionMap{})
	pulumi.RegisterOutputType(SecretVersionOutput{})
	pulumi.RegisterOutputType(SecretVersionArrayOutput{})
	pulumi.RegisterOutputType(SecretVersionMapOutput{})
}
