// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package thalassa

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/sandervb2/pulumi-thalassa/sdk/go/thalassa/internal"
)

// Manages egress rules for a security group using the batch API. This resource replaces all egress rules for the security group. This is an optional alternative to managing rules through the SecurityGroup resource. Warning: Do not use both this resource and egressRule in SecurityGroup for the same security group, as this will cause conflicts.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/sandervb2/pulumi-thalassa/sdk/go/thalassa"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			// Create a VPC for the security group
//			example, err := thalassa.NewVpc(ctx, "example", &thalassa.VpcArgs{
//				Name:        pulumi.String("example-vpc"),
//				Description: pulumi.String("Example VPC for security group egress rules"),
//				Region:      pulumi.String("nl-01"),
//				Cidrs: pulumi.StringArray{
//					pulumi.String("10.0.0.0/16"),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			// Create a security group
//			exampleSecurityGroup, err := thalassa.NewSecurityGroup(ctx, "example", &thalassa.SecurityGroupArgs{
//				Name:                  pulumi.String("example-security-group"),
//				Description:           pulumi.String("Example security group"),
//				VpcId:                 example.ID(),
//				AllowSameGroupTraffic: pulumi.Bool(false),
//			})
//			if err != nil {
//				return err
//			}
//			// Create egress rules for the security group
//			_, err = thalassa.NewSecurityGroupEgressRule(ctx, "example", &thalassa.SecurityGroupEgressRuleArgs{
//				SecurityGroupId: exampleSecurityGroup.ID(),
//				Rules: thalassa.SecurityGroupEgressRuleRuleArray{
//					&thalassa.SecurityGroupEgressRuleRuleArgs{
//						Name:          pulumi.String("allow-all-outbound"),
//						IpVersion:     pulumi.String("ipv4"),
//						Protocol:      pulumi.String("all"),
//						Priority:      pulumi.Int(100),
//						RemoteType:    pulumi.String("address"),
//						RemoteAddress: pulumi.String("0.0.0.0/0"),
//						Policy:        pulumi.String("allow"),
//					},
//					&thalassa.SecurityGroupEgressRuleRuleArgs{
//						Name:          pulumi.String("allow-https-outbound"),
//						IpVersion:     pulumi.String("ipv4"),
//						Protocol:      pulumi.String("tcp"),
//						Priority:      pulumi.Int(101),
//						RemoteType:    pulumi.String("address"),
//						RemoteAddress: pulumi.String("0.0.0.0/0"),
//						PortRangeMin:  pulumi.Int(443),
//						PortRangeMax:  pulumi.Int(443),
//						Policy:        pulumi.String("allow"),
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			ctx.Export("securityGroupId", exampleSecurityGroup.ID())
//			return nil
//		})
//	}
//
// ```
type SecurityGroupEgressRule struct {
	pulumi.CustomResourceState

	// List of egress rules for the security group
	Rules SecurityGroupEgressRuleRuleArrayOutput `pulumi:"rules"`
	// ID of the Security Group to manage egress rules for
	SecurityGroupId pulumi.StringOutput `pulumi:"securityGroupId"`
}

// NewSecurityGroupEgressRule registers a new resource with the given unique name, arguments, and options.
func NewSecurityGroupEgressRule(ctx *pulumi.Context,
	name string, args *SecurityGroupEgressRuleArgs, opts ...pulumi.ResourceOption) (*SecurityGroupEgressRule, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.SecurityGroupId == nil {
		return nil, errors.New("invalid value for required argument 'SecurityGroupId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource SecurityGroupEgressRule
	err := ctx.RegisterResource("thalassa:index/securityGroupEgressRule:SecurityGroupEgressRule", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSecurityGroupEgressRule gets an existing SecurityGroupEgressRule resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSecurityGroupEgressRule(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SecurityGroupEgressRuleState, opts ...pulumi.ResourceOption) (*SecurityGroupEgressRule, error) {
	var resource SecurityGroupEgressRule
	err := ctx.ReadResource("thalassa:index/securityGroupEgressRule:SecurityGroupEgressRule", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SecurityGroupEgressRule resources.
type securityGroupEgressRuleState struct {
	// List of egress rules for the security group
	Rules []SecurityGroupEgressRuleRule `pulumi:"rules"`
	// ID of the Security Group to manage egress rules for
	SecurityGroupId *string `pulumi:"securityGroupId"`
}

type SecurityGroupEgressRuleState struct {
	// List of egress rules for the security group
	Rules SecurityGroupEgressRuleRuleArrayInput
	// ID of the Security Group to manage egress rules for
	SecurityGroupId pulumi.StringPtrInput
}

func (SecurityGroupEgressRuleState) ElementType() reflect.Type {
	return reflect.TypeOf((*securityGroupEgressRuleState)(nil)).Elem()
}

type securityGroupEgressRuleArgs struct {
	// List of egress rules for the security group
	Rules []SecurityGroupEgressRuleRule `pulumi:"rules"`
	// ID of the Security Group to manage egress rules for
	SecurityGroupId string `pulumi:"securityGroupId"`
}

// The set of arguments for constructing a SecurityGroupEgressRule resource.
type SecurityGroupEgressRuleArgs struct {
	// List of egress rules for the security group
	Rules SecurityGroupEgressRuleRuleArrayInput
	// ID of the Security Group to manage egress rules for
	SecurityGroupId pulumi.StringInput
}

func (SecurityGroupEgressRuleArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*securityGroupEgressRuleArgs)(nil)).Elem()
}

type SecurityGroupEgressRuleInput interface {
	pulumi.Input

	ToSecurityGroupEgressRuleOutput() SecurityGroupEgressRuleOutput
	ToSecurityGroupEgressRuleOutputWithContext(ctx context.Context) SecurityGroupEgressRuleOutput
}

func (*SecurityGroupEgressRule) ElementType() reflect.Type {
	return reflect.TypeOf((**SecurityGroupEgressRule)(nil)).Elem()
}

func (i *SecurityGroupEgressRule) ToSecurityGroupEgressRuleOutput() SecurityGroupEgressRuleOutput {
	return i.ToSecurityGroupEgressRuleOutputWithContext(context.Background())
}

func (i *SecurityGroupEgressRule) ToSecurityGroupEgressRuleOutputWithContext(ctx context.Context) SecurityGroupEgressRuleOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SecurityGroupEgressRuleOutput)
}

// SecurityGroupEgressRuleArrayInput is an input type that accepts SecurityGroupEgressRuleArray and SecurityGroupEgressRuleArrayOutput values.
// You can construct a concrete instance of `SecurityGroupEgressRuleArrayInput` via:
//
//	SecurityGroupEgressRuleArray{ SecurityGroupEgressRuleArgs{...} }
type SecurityGroupEgressRuleArrayInput interface {
	pulumi.Input

	ToSecurityGroupEgressRuleArrayOutput() SecurityGroupEgressRuleArrayOutput
	ToSecurityGroupEgressRuleArrayOutputWithContext(context.Context) SecurityGroupEgressRuleArrayOutput
}

type SecurityGroupEgressRuleArray []SecurityGroupEgressRuleInput

func (SecurityGroupEgressRuleArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SecurityGroupEgressRule)(nil)).Elem()
}

func (i SecurityGroupEgressRuleArray) ToSecurityGroupEgressRuleArrayOutput() SecurityGroupEgressRuleArrayOutput {
	return i.ToSecurityGroupEgressRuleArrayOutputWithContext(context.Background())
}

func (i SecurityGroupEgressRuleArray) ToSecurityGroupEgressRuleArrayOutputWithContext(ctx context.Context) SecurityGroupEgressRuleArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SecurityGroupEgressRuleArrayOutput)
}

// SecurityGroupEgressRuleMapInput is an input type that accepts SecurityGroupEgressRuleMap and SecurityGroupEgressRuleMapOutput values.
// You can construct a concrete instance of `SecurityGroupEgressRuleMapInput` via:
//
//	SecurityGroupEgressRuleMap{ "key": SecurityGroupEgressRuleArgs{...} }
type SecurityGroupEgressRuleMapInput interface {
	pulumi.Input

	ToSecurityGroupEgressRuleMapOutput() SecurityGroupEgressRuleMapOutput
	ToSecurityGroupEgressRuleMapOutputWithContext(context.Context) SecurityGroupEgressRuleMapOutput
}

type SecurityGroupEgressRuleMap map[string]SecurityGroupEgressRuleInput

func (SecurityGroupEgressRuleMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SecurityGroupEgressRule)(nil)).Elem()
}

func (i SecurityGroupEgressRuleMap) ToSecurityGroupEgressRuleMapOutput() SecurityGroupEgressRuleMapOutput {
	return i.ToSecurityGroupEgressRuleMapOutputWithContext(context.Background())
}

func (i SecurityGroupEgressRuleMap) ToSecurityGroupEgressRuleMapOutputWithContext(ctx context.Context) SecurityGroupEgressRuleMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SecurityGroupEgressRuleMapOutput)
}

type SecurityGroupEgressRuleOutput struct{ *pulumi.OutputState }

func (SecurityGroupEgressRuleOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SecurityGroupEgressRule)(nil)).Elem()
}

func (o SecurityGroupEgressRuleOutput) ToSecurityGroupEgressRuleOutput() SecurityGroupEgressRuleOutput {
	return o
}

func (o SecurityGroupEgressRuleOutput) ToSecurityGroupEgressRuleOutputWithContext(ctx context.Context) SecurityGroupEgressRuleOutput {
	return o
}

// List of egress rules for the security group
func (o SecurityGroupEgressRuleOutput) Rules() SecurityGroupEgressRuleRuleArrayOutput {
	return o.ApplyT(func(v *SecurityGroupEgressRule) SecurityGroupEgressRuleRuleArrayOutput { return v.Rules }).(SecurityGroupEgressRuleRuleArrayOutput)
}

// ID of the Security Group to manage egress rules for
func (o SecurityGroupEgressRuleOutput) SecurityGroupId() pulumi.StringOutput {
	return o.ApplyT(func(v *SecurityGroupEgressRule) pulumi.StringOutput { return v.SecurityGroupId }).(pulumi.StringOutput)
}

type SecurityGroupEgressRuleArrayOutput struct{ *pulumi.OutputState }

func (SecurityGroupEgressRuleArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SecurityGroupEgressRule)(nil)).Elem()
}

func (o SecurityGroupEgressRuleArrayOutput) ToSecurityGroupEgressRuleArrayOutput() SecurityGroupEgressRuleArrayOutput {
	return o
}

func (o SecurityGroupEgressRuleArrayOutput) ToSecurityGroupEgressRuleArrayOutputWithContext(ctx context.Context) SecurityGroupEgressRuleArrayOutput {
	return o
}

func (o SecurityGroupEgressRuleArrayOutput) Index(i pulumi.IntInput) SecurityGroupEgressRuleOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *SecurityGroupEgressRule {
		return vs[0].([]*SecurityGroupEgressRule)[vs[1].(int)]
	}).(SecurityGroupEgressRuleOutput)
}

type SecurityGroupEgressRuleMapOutput struct{ *pulumi.OutputState }

func (SecurityGroupEgressRuleMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SecurityGroupEgressRule)(nil)).Elem()
}

func (o SecurityGroupEgressRuleMapOutput) ToSecurityGroupEgressRuleMapOutput() SecurityGroupEgressRuleMapOutput {
	return o
}

func (o SecurityGroupEgressRuleMapOutput) ToSecurityGroupEgressRuleMapOutputWithContext(ctx context.Context) SecurityGroupEgressRuleMapOutput {
	return o
}

func (o SecurityGroupEgressRuleMapOutput) MapIndex(k pulumi.StringInput) SecurityGroupEgressRuleOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *SecurityGroupEgressRule {
		return vs[0].(map[string]*SecurityGroupEgressRule)[vs[1].(string)]
	}).(SecurityGroupEgressRuleOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SecurityGroupEgressRuleInput)(nil)).Elem(), &SecurityGroupEgressRule{})
	pulumi.RegisterInputType(reflect.TypeOf((*SecurityGroupEgressRuleArrayInput)(nil)).Elem(), SecurityGroupEgressRuleArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*SecurityGroupEgressRuleMapInput)(nil)).Elem(), SecurityGroupEgressRuleMap{})
	pulumi.RegisterOutputType(SecurityGroupEgressRuleOutput{})
	pulumi.RegisterOutputType(SecurityGroupEgressRuleArrayOutput{})
	pulumi.RegisterOutputType(SecurityGroupEgressRuleMapOutput{})
}
