// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Thalassa.Outputs
{

    [OutputType]
    public sealed class DbaasDbClusterRestoreRecoveryTarget
    {
        /// <summary>
        /// Log Sequence Number to restore to. Example: '0/1234567'
        /// </summary>
        public readonly string? TargetLsn;
        /// <summary>
        /// Timestamp to restore to (RFC3339 format). Example: '2023-12-25T10:00:00Z'
        /// </summary>
        public readonly string? TargetTime;

        [OutputConstructor]
        private DbaasDbClusterRestoreRecoveryTarget(
            string? targetLsn,

            string? targetTime)
        {
            TargetLsn = targetLsn;
            TargetTime = targetTime;
        }
    }
}
