// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Thalassa.Outputs
{

    [OutputType]
    public sealed class GetIamOrganisationMembersMemberResult
    {
        /// <summary>
        /// Creation timestamp of the organisation member
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// Identity of the organisation member
        /// </summary>
        public readonly string Identity;
        /// <summary>
        /// Type of the organisation member (OWNER or MEMBER)
        /// </summary>
        public readonly string MemberType;
        /// <summary>
        /// User information for the organisation member
        /// </summary>
        public readonly ImmutableArray<Outputs.GetIamOrganisationMembersMemberUserResult> Users;

        [OutputConstructor]
        private GetIamOrganisationMembersMemberResult(
            string createdAt,

            string identity,

            string memberType,

            ImmutableArray<Outputs.GetIamOrganisationMembersMemberUserResult> users)
        {
            CreatedAt = createdAt;
            Identity = identity;
            MemberType = memberType;
            Users = users;
        }
    }
}
