// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Thalassa.Outputs
{

    [OutputType]
    public sealed class GetVpcFirewallRulesFirewallRuleResult
    {
        /// <summary>
        /// Action of the firewall rule (allow or drop)
        /// </summary>
        public readonly string Action;
        /// <summary>
        /// Time when the firewall rule was created
        /// </summary>
        public readonly string CreatedAt;
        /// <summary>
        /// Destination CIDR of the firewall rule
        /// </summary>
        public readonly string Destination;
        /// <summary>
        /// Destination ports of the firewall rule
        /// </summary>
        public readonly ImmutableArray<int> DestinationPorts;
        /// <summary>
        /// Identity of the destination subnet
        /// </summary>
        public readonly string DestinationSubnetId;
        /// <summary>
        /// Direction of the firewall rule (inbound or outbound)
        /// </summary>
        public readonly string Direction;
        /// <summary>
        /// Identity of the VPC firewall rule
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Identity of the interface
        /// </summary>
        public readonly string InterfaceId;
        /// <summary>
        /// Name of the VPC firewall rule
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Priority of the firewall rule
        /// </summary>
        public readonly int Priority;
        /// <summary>
        /// Protocols that the firewall rule applies to
        /// </summary>
        public readonly ImmutableArray<Outputs.GetVpcFirewallRulesFirewallRuleProtocolResult> Protocols;
        /// <summary>
        /// Source CIDR of the firewall rule
        /// </summary>
        public readonly string Source;
        /// <summary>
        /// Source ports of the firewall rule
        /// </summary>
        public readonly ImmutableArray<int> SourcePorts;
        /// <summary>
        /// Identity of the source subnet
        /// </summary>
        public readonly string SourceSubnetId;
        /// <summary>
        /// State of the firewall rule
        /// </summary>
        public readonly string State;

        [OutputConstructor]
        private GetVpcFirewallRulesFirewallRuleResult(
            string action,

            string createdAt,

            string destination,

            ImmutableArray<int> destinationPorts,

            string destinationSubnetId,

            string direction,

            string id,

            string interfaceId,

            string name,

            int priority,

            ImmutableArray<Outputs.GetVpcFirewallRulesFirewallRuleProtocolResult> protocols,

            string source,

            ImmutableArray<int> sourcePorts,

            string sourceSubnetId,

            string state)
        {
            Action = action;
            CreatedAt = createdAt;
            Destination = destination;
            DestinationPorts = destinationPorts;
            DestinationSubnetId = destinationSubnetId;
            Direction = direction;
            Id = id;
            InterfaceId = interfaceId;
            Name = name;
            Priority = priority;
            Protocols = protocols;
            Source = source;
            SourcePorts = sourcePorts;
            SourceSubnetId = sourceSubnetId;
            State = state;
        }
    }
}
