// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Thalassa.Outputs
{

    [OutputType]
    public sealed class IamTeamMember
    {
        /// <summary>
        /// Email address of the user to add to the team. If provided, UserIdentity will be resolved automatically.
        /// </summary>
        public readonly string? Email;
        /// <summary>
        /// Role of the team member. Optional. Default: MEMBER.
        /// </summary>
        public readonly string? Role;
        /// <summary>
        /// Identity of the user to add to the team
        /// </summary>
        public readonly string? UserIdentity;

        [OutputConstructor]
        private IamTeamMember(
            string? email,

            string? role,

            string? userIdentity)
        {
            Email = email;
            Role = role;
            UserIdentity = userIdentity;
        }
    }
}
