// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Thalassa.Outputs
{

    [OutputType]
    public sealed class KubernetesClusterAutoscalerConfig
    {
        /// <summary>
        /// Flag to balance the utilization of similar node groups by the cluster autoscaler
        /// </summary>
        public readonly bool? BalanceSimilarNodeGroups;
        /// <summary>
        /// Flag to enable the proactive scale up of the cluster autoscaler. Whether to enable/disable proactive scale-ups, defaults to false
        /// </summary>
        public readonly bool? EnableProactiveScaleUp;
        /// <summary>
        /// Estimator to use for the cluster autoscaler. Available values: binpacking
        /// </summary>
        public readonly string? Estimator;
        /// <summary>
        /// Expander to use for the cluster autoscaler
        /// </summary>
        public readonly string? Expander;
        /// <summary>
        /// Priority cutoff for the expendable pods by the cluster autoscaler
        /// </summary>
        public readonly int? ExpendablePodsPriorityCutoff;
        /// <summary>
        /// Flag to ignore the utilization of daemonsets by the cluster autoscaler
        /// </summary>
        public readonly bool? IgnoreDaemonsetsUtilization;
        /// <summary>
        /// Maximum graceful termination time for the cluster autoscaler. If the pod is not stopped within this time then the node is terminated anyway.
        /// </summary>
        public readonly int? MaxGracefulTerminationSec;
        /// <summary>
        /// Delay after adding a node to the node pool by the cluster autoscaler
        /// </summary>
        public readonly string? ScaleDownDelayAfterAdd;
        /// <summary>
        /// Flag to disable the scale down of node pools by the cluster autoscaler
        /// </summary>
        public readonly bool? ScaleDownDisabled;
        /// <summary>
        /// Time after which a node can be scaled down by the cluster autoscaler
        /// </summary>
        public readonly string? ScaleDownUnneededTime;
        /// <summary>
        /// Utilization threshold for the cluster autoscaler. The autoscaler might scale down non-empty nodes with utilization below a threshold. To prevent this behavior, set the utilization threshold to 0
        /// </summary>
        public readonly double? ScaleDownUtilizationThreshold;

        [OutputConstructor]
        private KubernetesClusterAutoscalerConfig(
            bool? balanceSimilarNodeGroups,

            bool? enableProactiveScaleUp,

            string? estimator,

            string? expander,

            int? expendablePodsPriorityCutoff,

            bool? ignoreDaemonsetsUtilization,

            int? maxGracefulTerminationSec,

            string? scaleDownDelayAfterAdd,

            bool? scaleDownDisabled,

            string? scaleDownUnneededTime,

            double? scaleDownUtilizationThreshold)
        {
            BalanceSimilarNodeGroups = balanceSimilarNodeGroups;
            EnableProactiveScaleUp = enableProactiveScaleUp;
            Estimator = estimator;
            Expander = expander;
            ExpendablePodsPriorityCutoff = expendablePodsPriorityCutoff;
            IgnoreDaemonsetsUtilization = ignoreDaemonsetsUtilization;
            MaxGracefulTerminationSec = maxGracefulTerminationSec;
            ScaleDownDelayAfterAdd = scaleDownDelayAfterAdd;
            ScaleDownDisabled = scaleDownDisabled;
            ScaleDownUnneededTime = scaleDownUnneededTime;
            ScaleDownUtilizationThreshold = scaleDownUtilizationThreshold;
        }
    }
}
