// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Thalassa.Outputs
{

    [OutputType]
    public sealed class KubernetesClusterApiServerAcl
    {
        /// <summary>
        /// List of allowed CIDRs for API server access
        /// </summary>
        public readonly ImmutableArray<string> AllowedCidrs;

        [OutputConstructor]
        private KubernetesClusterApiServerAcl(ImmutableArray<string> allowedCidrs)
        {
            AllowedCidrs = allowedCidrs;
        }
    }
}
