// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Thalassa.Outputs
{

    [OutputType]
    public sealed class KubernetesNodePoolNodeTaint
    {
        /// <summary>
        /// Effect of the taint
        /// </summary>
        public readonly string? Effect;
        /// <summary>
        /// Key of the taint
        /// </summary>
        public readonly string? Key;
        /// <summary>
        /// Operator of the taint
        /// </summary>
        public readonly string? Operator;
        /// <summary>
        /// Value of the taint. Optional.
        /// </summary>
        public readonly string? Value;

        [OutputConstructor]
        private KubernetesNodePoolNodeTaint(
            string? effect,

            string? key,

            string? @operator,

            string? value)
        {
            Effect = effect;
            Key = key;
            Operator = @operator;
            Value = value;
        }
    }
}
