// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Thalassa.Outputs
{

    [OutputType]
    public sealed class ObjectstorageBucketLifecycleRuleExpiration
    {
        public readonly string? Date;
        public readonly int? Days;
        public readonly bool? ExpiredObjectDeleteMarker;

        [OutputConstructor]
        private ObjectstorageBucketLifecycleRuleExpiration(
            string? date,

            int? days,

            bool? expiredObjectDeleteMarker)
        {
            Date = date;
            Days = days;
            ExpiredObjectDeleteMarker = expiredObjectDeleteMarker;
        }
    }
}
