// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Thalassa.Outputs
{

    [OutputType]
    public sealed class SnapshotPolicyTarget
    {
        /// <summary>
        /// Label selector for volumes (required when type is 'selector')
        /// </summary>
        public readonly ImmutableDictionary<string, string>? Selector;
        /// <summary>
        /// Type of target: 'selector' to target volumes based on labels, or 'explicit' to target specific volumes
        /// </summary>
        public readonly string Type;
        /// <summary>
        /// List of volume identities (required when type is 'explicit')
        /// </summary>
        public readonly ImmutableArray<string> VolumeIdentities;

        [OutputConstructor]
        private SnapshotPolicyTarget(
            ImmutableDictionary<string, string>? selector,

            string type,

            ImmutableArray<string> volumeIdentities)
        {
            Selector = selector;
            Type = type;
            VolumeIdentities = volumeIdentities;
        }
    }
}
