// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Thalassa.Outputs
{

    [OutputType]
    public sealed class TargetGroupAttachment
    {
        /// <summary>
        /// The ID of the target (e.g. instance ID)
        /// </summary>
        public readonly string Id;

        [OutputConstructor]
        private TargetGroupAttachment(string id)
        {
            Id = id;
        }
    }
}
