// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Thalassa.Inputs
{

    public sealed class KubernetesNodePoolNodeTaintArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Effect of the taint
        /// </summary>
        [Input("effect")]
        public Input<string>? Effect { get; set; }

        /// <summary>
        /// Key of the taint
        /// </summary>
        [Input("key")]
        public Input<string>? Key { get; set; }

        /// <summary>
        /// Operator of the taint
        /// </summary>
        [Input("operator")]
        public Input<string>? Operator { get; set; }

        /// <summary>
        /// Value of the taint. Optional.
        /// </summary>
        [Input("value")]
        public Input<string>? Value { get; set; }

        public KubernetesNodePoolNodeTaintArgs()
        {
        }
        public static new KubernetesNodePoolNodeTaintArgs Empty => new KubernetesNodePoolNodeTaintArgs();
    }
}
