// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Thalassa.Inputs
{

    public sealed class ObjectstorageBucketLifecycleRuleFilterArgs : global::Pulumi.ResourceArgs
    {
        [Input("and")]
        public Input<Inputs.ObjectstorageBucketLifecycleRuleFilterAndArgs>? And { get; set; }

        [Input("objectSizeGreaterThan")]
        public Input<int>? ObjectSizeGreaterThan { get; set; }

        [Input("objectSizeLessThan")]
        public Input<int>? ObjectSizeLessThan { get; set; }

        [Input("prefix")]
        public Input<string>? Prefix { get; set; }

        [Input("tag")]
        public Input<Inputs.ObjectstorageBucketLifecycleRuleFilterTagArgs>? Tag { get; set; }

        public ObjectstorageBucketLifecycleRuleFilterArgs()
        {
        }
        public static new ObjectstorageBucketLifecycleRuleFilterArgs Empty => new ObjectstorageBucketLifecycleRuleFilterArgs();
    }
}
