// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Thalassa.Inputs
{

    public sealed class TargetGroupAttachmentArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The ID of the target (e.g. instance ID)
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        public TargetGroupAttachmentArgs()
        {
        }
        public static new TargetGroupAttachmentArgs Empty => new TargetGroupAttachmentArgs();
    }
}
