name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

env:
  PROVIDER: thalassa
  GO111MODULE: "on"
  PROVIDER_VERSION: ${{ github.ref_name }}

jobs:
  publish_provider:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-go@v5
        with:
          go-version: "1.25.x"
          cache-dependency-path: "**/*.sum"
          
      - name: Set PROVIDER_VERSION from tag
        run: echo "PROVIDER_VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Build provider distributions
        run: |
          make clean
          make tfgen
          make provider_dist PROVIDER_VERSION="$PROVIDER_VERSION"

      - name: Upload provider assets to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            bin/pulumi-resource-thalassa-v${{ env.PROVIDER_VERSION }}-*.tar.gz
            bin/SHA256SUMS.txt
          overwrite: true

