name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

env:
  PROVIDER: thalassa
  GO111MODULE: "on"

jobs:
  publish_provider:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-go@v5
        with:
          go-version: "1.25.x"
          cache-dependency-path: "**/*.sum"

      - name: Build provider distributions
        run: |
          make clean
          make tfgen
          make provider_dist

      - name: Upload provider assets to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}   # e.g. v0.2.0
          files: |
            dist/pulumi-resource-thalassa-*.tar.gz
            dist/*_checksums.txt
