// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Create a PostgreSQL database
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as thalassa from "@pulumi/thalassa";
 *
 * // Create a VPC for the database cluster
 * const example = new thalassa.Vpc("example", {
 *     name: "example-vpc",
 *     description: "Example VPC for database cluster",
 *     region: "nl-01",
 *     cidrs: ["10.0.0.0/16"],
 * });
 * // Create a subnet for the database cluster
 * const exampleSubnet = new thalassa.Subnet("example", {
 *     name: "example-subnet",
 *     description: "Example subnet for database cluster",
 *     vpcId: example.id,
 *     cidr: "10.0.1.0/24",
 * });
 * // Create a database cluster for the PostgreSQL database
 * const exampleDbaasDbCluster = new thalassa.DbaasDbCluster("example", {
 *     name: "example-db-cluster",
 *     description: "Example database cluster for PostgreSQL database",
 *     subnetId: exampleSubnet.id,
 *     databaseInstanceType: "db-pgp-small",
 *     engine: "postgres",
 *     engineVersion: "15.13",
 *     allocatedStorage: 100,
 *     volumeTypeClass: "block",
 * });
 * // Create PostgreSQL roles first
 * const exampleDbaasPgRoles = new thalassa.DbaasPgRoles("example", {
 *     dbClusterId: exampleDbaasDbCluster.id,
 *     name: "myrole",
 *     password: "secure_password_123",
 * });
 * // Create a PostgreSQL database with Thalassa default values
 * const exampleDbaasPgDatabase = new thalassa.DbaasPgDatabase("example", {
 *     name: "mydatabase2",
 *     dbClusterId: exampleDbaasDbCluster.id,
 *     ownerRoleId: exampleDbaasPgRoles.id,
 * });
 * export const pgDatabaseId = exampleDbaasPgDatabase.id;
 * export const pgDatabaseName = exampleDbaasPgDatabase.name;
 * ```
 */
export class DbaasPgDatabase extends pulumi.CustomResource {
    /**
     * Get an existing DbaasPgDatabase resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DbaasPgDatabaseState, opts?: pulumi.CustomResourceOptions): DbaasPgDatabase {
        return new DbaasPgDatabase(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'thalassa:index/dbaasPgDatabase:DbaasPgDatabase';

    /**
     * Returns true if the given object is an instance of DbaasPgDatabase.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DbaasPgDatabase {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DbaasPgDatabase.__pulumiType;
    }

    /**
     * The connection limit of the database
     */
    declare public readonly connectionLimit: pulumi.Output<number | undefined>;
    /**
     * The ID of the database cluster
     */
    declare public readonly dbClusterId: pulumi.Output<string>;
    /**
     * The name of the database
     */
    declare public readonly name: pulumi.Output<string>;
    declare public readonly organisationId: pulumi.Output<string | undefined>;
    /**
     * The ID of the owner role
     */
    declare public readonly ownerRoleId: pulumi.Output<string>;

    /**
     * Create a DbaasPgDatabase resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DbaasPgDatabaseArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DbaasPgDatabaseArgs | DbaasPgDatabaseState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DbaasPgDatabaseState | undefined;
            resourceInputs["connectionLimit"] = state?.connectionLimit;
            resourceInputs["dbClusterId"] = state?.dbClusterId;
            resourceInputs["name"] = state?.name;
            resourceInputs["organisationId"] = state?.organisationId;
            resourceInputs["ownerRoleId"] = state?.ownerRoleId;
        } else {
            const args = argsOrState as DbaasPgDatabaseArgs | undefined;
            if (args?.dbClusterId === undefined && !opts.urn) {
                throw new Error("Missing required property 'dbClusterId'");
            }
            if (args?.ownerRoleId === undefined && !opts.urn) {
                throw new Error("Missing required property 'ownerRoleId'");
            }
            resourceInputs["connectionLimit"] = args?.connectionLimit;
            resourceInputs["dbClusterId"] = args?.dbClusterId;
            resourceInputs["name"] = args?.name;
            resourceInputs["organisationId"] = args?.organisationId;
            resourceInputs["ownerRoleId"] = args?.ownerRoleId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(DbaasPgDatabase.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering DbaasPgDatabase resources.
 */
export interface DbaasPgDatabaseState {
    /**
     * The connection limit of the database
     */
    connectionLimit?: pulumi.Input<number>;
    /**
     * The ID of the database cluster
     */
    dbClusterId?: pulumi.Input<string>;
    /**
     * The name of the database
     */
    name?: pulumi.Input<string>;
    organisationId?: pulumi.Input<string>;
    /**
     * The ID of the owner role
     */
    ownerRoleId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a DbaasPgDatabase resource.
 */
export interface DbaasPgDatabaseArgs {
    /**
     * The connection limit of the database
     */
    connectionLimit?: pulumi.Input<number>;
    /**
     * The ID of the database cluster
     */
    dbClusterId: pulumi.Input<string>;
    /**
     * The name of the database
     */
    name?: pulumi.Input<string>;
    organisationId?: pulumi.Input<string>;
    /**
     * The ID of the owner role
     */
    ownerRoleId: pulumi.Input<string>;
}
