// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Get a temporary session token for authenticating with a Kubernetes cluster for the currently authenticated user or system account. This token can be used to access the cluster via kubectl or other Kubernetes tools.
 */
export function getKubernetesClusterSessionToken(args: GetKubernetesClusterSessionTokenArgs, opts?: pulumi.InvokeOptions): Promise<GetKubernetesClusterSessionTokenResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("thalassa:index/getKubernetesClusterSessionToken:getKubernetesClusterSessionToken", {
        "clusterId": args.clusterId,
        "organisationId": args.organisationId,
    }, opts);
}

/**
 * A collection of arguments for invoking getKubernetesClusterSessionToken.
 */
export interface GetKubernetesClusterSessionTokenArgs {
    /**
     * The ID of the Kubernetes cluster to get a session token for
     */
    clusterId: string;
    organisationId?: string;
}

/**
 * A collection of values returned by getKubernetesClusterSessionToken.
 */
export interface GetKubernetesClusterSessionTokenResult {
    /**
     * The URL of the Kubernetes API server
     */
    readonly apiServerUrl: string;
    /**
     * The CA certificate of the API server
     */
    readonly caCertificate: string;
    /**
     * The ID of the Kubernetes cluster to get a session token for
     */
    readonly clusterId: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * The complete kubeconfig file content for the session
     */
    readonly kubeconfig: string;
    readonly organisationId?: string;
    /**
     * The authentication token for the session
     */
    readonly token: string;
    /**
     * The username for cluster authentication
     */
    readonly username: string;
}
/**
 * Get a temporary session token for authenticating with a Kubernetes cluster for the currently authenticated user or system account. This token can be used to access the cluster via kubectl or other Kubernetes tools.
 */
export function getKubernetesClusterSessionTokenOutput(args: GetKubernetesClusterSessionTokenOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetKubernetesClusterSessionTokenResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("thalassa:index/getKubernetesClusterSessionToken:getKubernetesClusterSessionToken", {
        "clusterId": args.clusterId,
        "organisationId": args.organisationId,
    }, opts);
}

/**
 * A collection of arguments for invoking getKubernetesClusterSessionToken.
 */
export interface GetKubernetesClusterSessionTokenOutputArgs {
    /**
     * The ID of the Kubernetes cluster to get a session token for
     */
    clusterId: pulumi.Input<string>;
    organisationId?: pulumi.Input<string>;
}
