// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Get an machine image
 */
export function getMachineImage(args: GetMachineImageArgs, opts?: pulumi.InvokeOptions): Promise<GetMachineImageResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("thalassa:index/getMachineImage:getMachineImage", {
        "name": args.name,
        "organisationId": args.organisationId,
        "slug": args.slug,
    }, opts);
}

/**
 * A collection of arguments for invoking getMachineImage.
 */
export interface GetMachineImageArgs {
    /**
     * Name of the machine image
     */
    name: string;
    organisationId?: string;
    /**
     * Slug of the machine image
     */
    slug?: string;
}

/**
 * A collection of values returned by getMachineImage.
 */
export interface GetMachineImageResult {
    /**
     * Annotations of the machine image
     */
    readonly annotations: {[key: string]: string};
    /**
     * Description of the machine image
     */
    readonly description: string;
    /**
     * Identity of the machine image
     */
    readonly id: string;
    /**
     * Labels of the machine image
     */
    readonly labels: {[key: string]: string};
    /**
     * Name of the machine image
     */
    readonly name: string;
    readonly organisationId?: string;
    /**
     * Slug of the machine image
     */
    readonly slug?: string;
}
/**
 * Get an machine image
 */
export function getMachineImageOutput(args: GetMachineImageOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetMachineImageResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("thalassa:index/getMachineImage:getMachineImage", {
        "name": args.name,
        "organisationId": args.organisationId,
        "slug": args.slug,
    }, opts);
}

/**
 * A collection of arguments for invoking getMachineImage.
 */
export interface GetMachineImageOutputArgs {
    /**
     * Name of the machine image
     */
    name: pulumi.Input<string>;
    organisationId?: pulumi.Input<string>;
    /**
     * Slug of the machine image
     */
    slug?: pulumi.Input<string>;
}
