// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Get a VPC route table
 */
export function getRouteTable(args?: GetRouteTableArgs, opts?: pulumi.InvokeOptions): Promise<GetRouteTableResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("thalassa:index/getRouteTable:getRouteTable", {
        "identity": args.identity,
        "isDefault": args.isDefault,
        "labelSelector": args.labelSelector,
        "name": args.name,
        "vpcId": args.vpcId,
    }, opts);
}

/**
 * A collection of arguments for invoking getRouteTable.
 */
export interface GetRouteTableArgs {
    /**
     * ID of the route table
     */
    identity?: string;
    /**
     * Filter by default route table
     */
    isDefault?: boolean;
    /**
     * Match route tables that have all provided labels (exact key=value match)
     */
    labelSelector?: {[key: string]: string};
    /**
     * Name of the route table
     */
    name?: string;
    /**
     * ID of the VPC for the route table
     */
    vpcId?: string;
}

/**
 * A collection of values returned by getRouteTable.
 */
export interface GetRouteTableResult {
    /**
     * Annotations on the route table
     */
    readonly annotations: {[key: string]: string};
    /**
     * Creation time
     */
    readonly createdAt: string;
    /**
     * Description of the route table
     */
    readonly description: string;
    /**
     * The ID of this resource.
     */
    readonly id: string;
    /**
     * ID of the route table
     */
    readonly identity?: string;
    /**
     * Filter by default route table
     */
    readonly isDefault?: boolean;
    /**
     * Match route tables that have all provided labels (exact key=value match)
     */
    readonly labelSelector?: {[key: string]: string};
    /**
     * Labels on the route table
     */
    readonly labels: {[key: string]: string};
    /**
     * Name of the route table
     */
    readonly name?: string;
    readonly slug: string;
    /**
     * Last update time
     */
    readonly updatedAt: string;
    /**
     * ID of the VPC for the route table
     */
    readonly vpcId?: string;
}
/**
 * Get a VPC route table
 */
export function getRouteTableOutput(args?: GetRouteTableOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetRouteTableResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("thalassa:index/getRouteTable:getRouteTable", {
        "identity": args.identity,
        "isDefault": args.isDefault,
        "labelSelector": args.labelSelector,
        "name": args.name,
        "vpcId": args.vpcId,
    }, opts);
}

/**
 * A collection of arguments for invoking getRouteTable.
 */
export interface GetRouteTableOutputArgs {
    /**
     * ID of the route table
     */
    identity?: pulumi.Input<string>;
    /**
     * Filter by default route table
     */
    isDefault?: pulumi.Input<boolean>;
    /**
     * Match route tables that have all provided labels (exact key=value match)
     */
    labelSelector?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Name of the route table
     */
    name?: pulumi.Input<string>;
    /**
     * ID of the VPC for the route table
     */
    vpcId?: pulumi.Input<string>;
}
