// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Manage object storage bucket lifecycle rules. Each apply replaces the full rule set.
 *
 * Each apply **replaces the entire rule set** (`SetBucketLifecycle` PUT semantics). Ongoing lifecycle management should use this resource, not `thalassa.ObjectstorageBucket`.
 *
 * Noncurrent version rules require bucket versioning `Enabled`.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as thalassa from "@sandervb2/pulumi-thalassa";
 *
 * const logs = new thalassa.ObjectstorageBucket("logs", {
 *     name: "my-logs-bucket",
 *     region: "nl-01",
 *     versioning: true,
 * });
 * const logsObjectstorageBucketLifecycle = new thalassa.ObjectstorageBucketLifecycle("logs", {
 *     bucketName: logs.name,
 *     rules: [{
 *         id: "expire-logs",
 *         prefix: "logs/",
 *         status: "Enabled",
 *         expiration: {
 *             days: 30,
 *         },
 *     }],
 * });
 * ```
 *
 * ## Import
 *
 * Import ID: `{bucket_name}`.
 *
 * !/bin/bash
 * Example: terraform import thalassa_objectstorage_bucket_lifecycle.logs my-logs-bucket
 *
 * ```sh
 * $ pulumi import thalassa:index/objectstorageBucketLifecycle:ObjectstorageBucketLifecycle logs my-logs-bucket
 * ```
 */
export class ObjectstorageBucketLifecycle extends pulumi.CustomResource {
    /**
     * Get an existing ObjectstorageBucketLifecycle resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ObjectstorageBucketLifecycleState, opts?: pulumi.CustomResourceOptions): ObjectstorageBucketLifecycle {
        return new ObjectstorageBucketLifecycle(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'thalassa:index/objectstorageBucketLifecycle:ObjectstorageBucketLifecycle';

    /**
     * Returns true if the given object is an instance of ObjectstorageBucketLifecycle.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ObjectstorageBucketLifecycle {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ObjectstorageBucketLifecycle.__pulumiType;
    }

    /**
     * Name of the bucket.
     */
    declare public readonly bucketName: pulumi.Output<string>;
    declare public readonly organisationId: pulumi.Output<string | undefined>;
    declare public readonly rules: pulumi.Output<outputs.ObjectstorageBucketLifecycleRule[]>;

    /**
     * Create a ObjectstorageBucketLifecycle resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ObjectstorageBucketLifecycleArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ObjectstorageBucketLifecycleArgs | ObjectstorageBucketLifecycleState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ObjectstorageBucketLifecycleState | undefined;
            resourceInputs["bucketName"] = state?.bucketName;
            resourceInputs["organisationId"] = state?.organisationId;
            resourceInputs["rules"] = state?.rules;
        } else {
            const args = argsOrState as ObjectstorageBucketLifecycleArgs | undefined;
            if (args?.bucketName === undefined && !opts.urn) {
                throw new Error("Missing required property 'bucketName'");
            }
            if (args?.rules === undefined && !opts.urn) {
                throw new Error("Missing required property 'rules'");
            }
            resourceInputs["bucketName"] = args?.bucketName;
            resourceInputs["organisationId"] = args?.organisationId;
            resourceInputs["rules"] = args?.rules;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ObjectstorageBucketLifecycle.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ObjectstorageBucketLifecycle resources.
 */
export interface ObjectstorageBucketLifecycleState {
    /**
     * Name of the bucket.
     */
    bucketName?: pulumi.Input<string | undefined>;
    organisationId?: pulumi.Input<string | undefined>;
    rules?: pulumi.Input<pulumi.Input<inputs.ObjectstorageBucketLifecycleRule>[] | undefined>;
}

/**
 * The set of arguments for constructing a ObjectstorageBucketLifecycle resource.
 */
export interface ObjectstorageBucketLifecycleArgs {
    /**
     * Name of the bucket.
     */
    bucketName: pulumi.Input<string>;
    organisationId?: pulumi.Input<string | undefined>;
    rules: pulumi.Input<pulumi.Input<inputs.ObjectstorageBucketLifecycleRule>[]>;
}
