// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Create an vpc
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as thalassa from "@pulumi/thalassa";
 *
 * // Create a VPC with all optional attributes
 * const example = new thalassa.Vpc("example", {
 *     name: "example-vpc",
 *     region: "nl-01",
 *     cidrs: [
 *         "10.0.0.0/16",
 *         "10.2.0.0/16",
 *         "10.3.0.0/16",
 *     ],
 *     description: "Example VPC for documentation with all optional attributes",
 *     labels: {
 *         environment: "production",
 *         project: "example-project",
 *         owner: "team-a",
 *     },
 * });
 * // Create a subnet within the VPC
 * const exampleSubnet = new thalassa.Subnet("example", {
 *     name: "example-subnet",
 *     description: "Example subnet for documentation",
 *     vpcId: example.id,
 *     cidr: "10.0.1.0/24",
 * });
 * export const vpcId = example.id;
 * export const subnetId = exampleSubnet.id;
 * ```
 */
export class Vpc extends pulumi.CustomResource {
    /**
     * Get an existing Vpc resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: VpcState, opts?: pulumi.CustomResourceOptions): Vpc {
        return new Vpc(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'thalassa:index/vpc:Vpc';

    /**
     * Returns true if the given object is an instance of Vpc.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Vpc {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Vpc.__pulumiType;
    }

    /**
     * Annotations for the Vpc
     */
    declare public readonly annotations: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * List of CIDRs for the Vpc
     */
    declare public readonly cidrs: pulumi.Output<string[]>;
    /**
     * A human readable description about the vpc
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * Labels for the Vpc
     */
    declare public readonly labels: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * Name of the Vpc
     */
    declare public readonly name: pulumi.Output<string>;
    declare public readonly organisationId: pulumi.Output<string | undefined>;
    /**
     * Region of the Vpc. Provide the identity of the region. Can only be set on creation.
     */
    declare public readonly region: pulumi.Output<string>;
    /**
     * Slug of the Vpc
     */
    declare public /*out*/ readonly slug: pulumi.Output<string>;
    /**
     * Status of the Vpc
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;

    /**
     * Create a Vpc resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: VpcArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: VpcArgs | VpcState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as VpcState | undefined;
            resourceInputs["annotations"] = state?.annotations;
            resourceInputs["cidrs"] = state?.cidrs;
            resourceInputs["description"] = state?.description;
            resourceInputs["labels"] = state?.labels;
            resourceInputs["name"] = state?.name;
            resourceInputs["organisationId"] = state?.organisationId;
            resourceInputs["region"] = state?.region;
            resourceInputs["slug"] = state?.slug;
            resourceInputs["status"] = state?.status;
        } else {
            const args = argsOrState as VpcArgs | undefined;
            if (args?.cidrs === undefined && !opts.urn) {
                throw new Error("Missing required property 'cidrs'");
            }
            if (args?.region === undefined && !opts.urn) {
                throw new Error("Missing required property 'region'");
            }
            resourceInputs["annotations"] = args?.annotations;
            resourceInputs["cidrs"] = args?.cidrs;
            resourceInputs["description"] = args?.description;
            resourceInputs["labels"] = args?.labels;
            resourceInputs["name"] = args?.name;
            resourceInputs["organisationId"] = args?.organisationId;
            resourceInputs["region"] = args?.region;
            resourceInputs["slug"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Vpc.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Vpc resources.
 */
export interface VpcState {
    /**
     * Annotations for the Vpc
     */
    annotations?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * List of CIDRs for the Vpc
     */
    cidrs?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * A human readable description about the vpc
     */
    description?: pulumi.Input<string>;
    /**
     * Labels for the Vpc
     */
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Name of the Vpc
     */
    name?: pulumi.Input<string>;
    organisationId?: pulumi.Input<string>;
    /**
     * Region of the Vpc. Provide the identity of the region. Can only be set on creation.
     */
    region?: pulumi.Input<string>;
    /**
     * Slug of the Vpc
     */
    slug?: pulumi.Input<string>;
    /**
     * Status of the Vpc
     */
    status?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Vpc resource.
 */
export interface VpcArgs {
    /**
     * Annotations for the Vpc
     */
    annotations?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * List of CIDRs for the Vpc
     */
    cidrs: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * A human readable description about the vpc
     */
    description?: pulumi.Input<string>;
    /**
     * Labels for the Vpc
     */
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Name of the Vpc
     */
    name?: pulumi.Input<string>;
    organisationId?: pulumi.Input<string>;
    /**
     * Region of the Vpc. Provide the identity of the region. Can only be set on creation.
     */
    region: pulumi.Input<string>;
}
