// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Create a VPC firewall rule
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as thalassa from "@sandervb2/pulumi-thalassa";
 *
 * // vpc
 * const vpc = new thalassa.Vpc("vpc", {
 *     region: "nl-01",
 *     cidrs: ["10.0.0.0/24"],
 * });
 * // Create a VPC firewall rule to allow SSH
 * const allowSsh = new thalassa.VpcFirewallRule("allowSsh", {
 *     vpcId: vpc.id,
 *     protocols: {
 *         tcp: true,
 *     },
 *     source: "0.0.0.0/0",
 *     destination: "10.0.0.0/8",
 *     destinationPorts: [22],
 *     action: "allow",
 *     priority: 100,
 *     direction: "inbound",
 *     state: "active",
 * });
 * // Create a VPC firewall rule to allow HTTP/HTTPS
 * const allowWeb = new thalassa.VpcFirewallRule("allowWeb", {
 *     vpcId: vpc.id,
 *     protocols: {
 *         tcp: true,
 *     },
 *     source: "0.0.0.0/0",
 *     destination: "10.0.0.0/8",
 *     destinationPorts: [
 *         80,
 *         443,
 *     ],
 *     action: "allow",
 *     priority: 200,
 *     direction: "inbound",
 *     state: "active",
 * });
 * ```
 */
export class VpcFirewallRule extends pulumi.CustomResource {
    /**
     * Get an existing VpcFirewallRule resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: VpcFirewallRuleState, opts?: pulumi.CustomResourceOptions): VpcFirewallRule {
        return new VpcFirewallRule(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'thalassa:index/vpcFirewallRule:VpcFirewallRule';

    /**
     * Returns true if the given object is an instance of VpcFirewallRule.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is VpcFirewallRule {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === VpcFirewallRule.__pulumiType;
    }

    /**
     * Action of the firewall rule. One of allow, drop
     */
    declare public readonly action: pulumi.Output<string>;
    /**
     * Time when the firewall rule was created
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * Destination CIDR of the firewall rule
     */
    declare public readonly destination: pulumi.Output<string | undefined>;
    /**
     * Destination ports of the firewall rule. Must be between 0 and 65535
     */
    declare public readonly destinationPorts: pulumi.Output<number[] | undefined>;
    /**
     * Identity of the destination subnet
     */
    declare public readonly destinationSubnetId: pulumi.Output<string | undefined>;
    /**
     * Direction of the firewall rule
     */
    declare public readonly direction: pulumi.Output<string>;
    /**
     * Identity of the interface. Leaving empty will apply to all interfaces
     */
    declare public readonly interfaceId: pulumi.Output<string | undefined>;
    /**
     * Name of the VPC firewall rule. Must be between 1 and 16 characters and contain only ASCII characters.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Priority of the firewall rule. Must be between 1 and 1000
     */
    declare public readonly priority: pulumi.Output<number>;
    /**
     * Protocols that the firewall rule applies to
     */
    declare public readonly protocols: pulumi.Output<outputs.VpcFirewallRuleProtocols>;
    /**
     * Source CIDR of the firewall rule
     */
    declare public readonly source: pulumi.Output<string | undefined>;
    /**
     * Source ports of the firewall rule. Must be between 0 and 65535
     */
    declare public readonly sourcePorts: pulumi.Output<number[] | undefined>;
    /**
     * Identity of the source subnet
     */
    declare public readonly sourceSubnetId: pulumi.Output<string | undefined>;
    /**
     * State of the firewall rule
     */
    declare public readonly state: pulumi.Output<string | undefined>;
    /**
     * Identity of the VPC that the firewall rule belongs to
     */
    declare public readonly vpcId: pulumi.Output<string>;

    /**
     * Create a VpcFirewallRule resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: VpcFirewallRuleArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: VpcFirewallRuleArgs | VpcFirewallRuleState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as VpcFirewallRuleState | undefined;
            resourceInputs["action"] = state?.action;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["destination"] = state?.destination;
            resourceInputs["destinationPorts"] = state?.destinationPorts;
            resourceInputs["destinationSubnetId"] = state?.destinationSubnetId;
            resourceInputs["direction"] = state?.direction;
            resourceInputs["interfaceId"] = state?.interfaceId;
            resourceInputs["name"] = state?.name;
            resourceInputs["priority"] = state?.priority;
            resourceInputs["protocols"] = state?.protocols;
            resourceInputs["source"] = state?.source;
            resourceInputs["sourcePorts"] = state?.sourcePorts;
            resourceInputs["sourceSubnetId"] = state?.sourceSubnetId;
            resourceInputs["state"] = state?.state;
            resourceInputs["vpcId"] = state?.vpcId;
        } else {
            const args = argsOrState as VpcFirewallRuleArgs | undefined;
            if (args?.action === undefined && !opts.urn) {
                throw new Error("Missing required property 'action'");
            }
            if (args?.direction === undefined && !opts.urn) {
                throw new Error("Missing required property 'direction'");
            }
            if (args?.priority === undefined && !opts.urn) {
                throw new Error("Missing required property 'priority'");
            }
            if (args?.protocols === undefined && !opts.urn) {
                throw new Error("Missing required property 'protocols'");
            }
            if (args?.vpcId === undefined && !opts.urn) {
                throw new Error("Missing required property 'vpcId'");
            }
            resourceInputs["action"] = args?.action;
            resourceInputs["destination"] = args?.destination;
            resourceInputs["destinationPorts"] = args?.destinationPorts;
            resourceInputs["destinationSubnetId"] = args?.destinationSubnetId;
            resourceInputs["direction"] = args?.direction;
            resourceInputs["interfaceId"] = args?.interfaceId;
            resourceInputs["name"] = args?.name;
            resourceInputs["priority"] = args?.priority;
            resourceInputs["protocols"] = args?.protocols;
            resourceInputs["source"] = args?.source;
            resourceInputs["sourcePorts"] = args?.sourcePorts;
            resourceInputs["sourceSubnetId"] = args?.sourceSubnetId;
            resourceInputs["state"] = args?.state;
            resourceInputs["vpcId"] = args?.vpcId;
            resourceInputs["createdAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(VpcFirewallRule.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering VpcFirewallRule resources.
 */
export interface VpcFirewallRuleState {
    /**
     * Action of the firewall rule. One of allow, drop
     */
    action?: pulumi.Input<string>;
    /**
     * Time when the firewall rule was created
     */
    createdAt?: pulumi.Input<string>;
    /**
     * Destination CIDR of the firewall rule
     */
    destination?: pulumi.Input<string>;
    /**
     * Destination ports of the firewall rule. Must be between 0 and 65535
     */
    destinationPorts?: pulumi.Input<pulumi.Input<number>[]>;
    /**
     * Identity of the destination subnet
     */
    destinationSubnetId?: pulumi.Input<string>;
    /**
     * Direction of the firewall rule
     */
    direction?: pulumi.Input<string>;
    /**
     * Identity of the interface. Leaving empty will apply to all interfaces
     */
    interfaceId?: pulumi.Input<string>;
    /**
     * Name of the VPC firewall rule. Must be between 1 and 16 characters and contain only ASCII characters.
     */
    name?: pulumi.Input<string>;
    /**
     * Priority of the firewall rule. Must be between 1 and 1000
     */
    priority?: pulumi.Input<number>;
    /**
     * Protocols that the firewall rule applies to
     */
    protocols?: pulumi.Input<inputs.VpcFirewallRuleProtocols>;
    /**
     * Source CIDR of the firewall rule
     */
    source?: pulumi.Input<string>;
    /**
     * Source ports of the firewall rule. Must be between 0 and 65535
     */
    sourcePorts?: pulumi.Input<pulumi.Input<number>[]>;
    /**
     * Identity of the source subnet
     */
    sourceSubnetId?: pulumi.Input<string>;
    /**
     * State of the firewall rule
     */
    state?: pulumi.Input<string>;
    /**
     * Identity of the VPC that the firewall rule belongs to
     */
    vpcId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a VpcFirewallRule resource.
 */
export interface VpcFirewallRuleArgs {
    /**
     * Action of the firewall rule. One of allow, drop
     */
    action: pulumi.Input<string>;
    /**
     * Destination CIDR of the firewall rule
     */
    destination?: pulumi.Input<string>;
    /**
     * Destination ports of the firewall rule. Must be between 0 and 65535
     */
    destinationPorts?: pulumi.Input<pulumi.Input<number>[]>;
    /**
     * Identity of the destination subnet
     */
    destinationSubnetId?: pulumi.Input<string>;
    /**
     * Direction of the firewall rule
     */
    direction: pulumi.Input<string>;
    /**
     * Identity of the interface. Leaving empty will apply to all interfaces
     */
    interfaceId?: pulumi.Input<string>;
    /**
     * Name of the VPC firewall rule. Must be between 1 and 16 characters and contain only ASCII characters.
     */
    name?: pulumi.Input<string>;
    /**
     * Priority of the firewall rule. Must be between 1 and 1000
     */
    priority: pulumi.Input<number>;
    /**
     * Protocols that the firewall rule applies to
     */
    protocols: pulumi.Input<inputs.VpcFirewallRuleProtocols>;
    /**
     * Source CIDR of the firewall rule
     */
    source?: pulumi.Input<string>;
    /**
     * Source ports of the firewall rule. Must be between 0 and 65535
     */
    sourcePorts?: pulumi.Input<pulumi.Input<number>[]>;
    /**
     * Identity of the source subnet
     */
    sourceSubnetId?: pulumi.Input<string>;
    /**
     * State of the firewall rule
     */
    state?: pulumi.Input<string>;
    /**
     * Identity of the VPC that the firewall rule belongs to
     */
    vpcId: pulumi.Input<string>;
}
