// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Accept a VPC peering connection
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as thalassa from "@sandervb2/pulumi-thalassa";
 *
 * // Create VPCs for peering
 * const requesterVpcVpc = new thalassa.Vpc("requesterVpcVpc", {
 *     region: "nl-01",
 *     cidrs: ["10.0.0.0/16"],
 * });
 * const accepterVpcVpc = new thalassa.Vpc("accepterVpcVpc", {
 *     region: "nl-01",
 *     cidrs: ["10.1.0.0/16"],
 * });
 * // Create VPC peering connection
 * const example = new thalassa.VpcPeeringConnection("example", {
 *     description: "Peering connection between two VPCs in the same region",
 *     requesterVpcId: requesterVpcVpc.id,
 *     accepterVpcId: accepterVpcVpc.id,
 *     autoAccept: false,
 * });
 * // # Example 1: Accept a peering connection by ID
 * const acceptById = new thalassa.VpcPeeringConnectionAcceptance("acceptById", {
 *     peeringConnectionId: example.id,
 *     waitForActive: true,
 *     waitForActiveTimeout: 1,
 * });
 * const requesterVpcVpcDefaultRouteTable = thalassa.getVpcDefaultRouteTableOutput({
 *     vpcId: requesterVpcVpc.id,
 * });
 * const accepterVpcVpcDefaultRouteTable = thalassa.getVpcDefaultRouteTableOutput({
 *     vpcId: accepterVpcVpc.id,
 * });
 * // Configure route table routes
 * // Important; routes can only be created after the peering connection has been accepted and has become active
 * const requesterVpcRouteTableRoute = new thalassa.RouteTableRoute("requesterVpcRouteTableRoute", {
 *     routeTableId: requesterVpcVpcDefaultRouteTable.apply(requesterVpcVpcDefaultRouteTable => requesterVpcVpcDefaultRouteTable.id),
 *     destinationCidr: accepterVpcVpc.cidrs[0],
 *     targetVpcPeeringConnection: acceptById.peeringConnectionId,
 * });
 * const accepterVpcRouteTableRoute = new thalassa.RouteTableRoute("accepterVpcRouteTableRoute", {
 *     routeTableId: accepterVpcVpcDefaultRouteTable.apply(accepterVpcVpcDefaultRouteTable => accepterVpcVpcDefaultRouteTable.id),
 *     destinationCidr: requesterVpcVpc.cidrs[0],
 *     targetVpcPeeringConnection: acceptById.peeringConnectionId,
 * });
 * ```
 */
export class VpcPeeringConnectionAcceptance extends pulumi.CustomResource {
    /**
     * Get an existing VpcPeeringConnectionAcceptance resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: VpcPeeringConnectionAcceptanceState, opts?: pulumi.CustomResourceOptions): VpcPeeringConnectionAcceptance {
        return new VpcPeeringConnectionAcceptance(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'thalassa:index/vpcPeeringConnectionAcceptance:VpcPeeringConnectionAcceptance';

    /**
     * Returns true if the given object is an instance of VpcPeeringConnectionAcceptance.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is VpcPeeringConnectionAcceptance {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === VpcPeeringConnectionAcceptance.__pulumiType;
    }

    /**
     * Identity of the VPC peering connection to accept
     */
    declare public readonly peeringConnectionId: pulumi.Output<string>;
    /**
     * Current status of the VPC peering connection after the action
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;
    /**
     * Additional information about the current status
     */
    declare public /*out*/ readonly statusMessage: pulumi.Output<string>;
    /**
     * Whether to wait for the VPC peering connection to be active
     */
    declare public readonly waitForActive: pulumi.Output<boolean | undefined>;
    /**
     * The timeout in minutes to wait for the VPC peering connection to be active
     */
    declare public readonly waitForActiveTimeout: pulumi.Output<number | undefined>;
    /**
     * The timeout in minutes to wait for the VPC peering connection to be deleted. Set to 0 to disable waiting.
     */
    declare public readonly waitForDeletedTimeout: pulumi.Output<number | undefined>;

    /**
     * Create a VpcPeeringConnectionAcceptance resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: VpcPeeringConnectionAcceptanceArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: VpcPeeringConnectionAcceptanceArgs | VpcPeeringConnectionAcceptanceState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as VpcPeeringConnectionAcceptanceState | undefined;
            resourceInputs["peeringConnectionId"] = state?.peeringConnectionId;
            resourceInputs["status"] = state?.status;
            resourceInputs["statusMessage"] = state?.statusMessage;
            resourceInputs["waitForActive"] = state?.waitForActive;
            resourceInputs["waitForActiveTimeout"] = state?.waitForActiveTimeout;
            resourceInputs["waitForDeletedTimeout"] = state?.waitForDeletedTimeout;
        } else {
            const args = argsOrState as VpcPeeringConnectionAcceptanceArgs | undefined;
            if (args?.peeringConnectionId === undefined && !opts.urn) {
                throw new Error("Missing required property 'peeringConnectionId'");
            }
            resourceInputs["peeringConnectionId"] = args?.peeringConnectionId;
            resourceInputs["waitForActive"] = args?.waitForActive;
            resourceInputs["waitForActiveTimeout"] = args?.waitForActiveTimeout;
            resourceInputs["waitForDeletedTimeout"] = args?.waitForDeletedTimeout;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["statusMessage"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(VpcPeeringConnectionAcceptance.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering VpcPeeringConnectionAcceptance resources.
 */
export interface VpcPeeringConnectionAcceptanceState {
    /**
     * Identity of the VPC peering connection to accept
     */
    peeringConnectionId?: pulumi.Input<string>;
    /**
     * Current status of the VPC peering connection after the action
     */
    status?: pulumi.Input<string>;
    /**
     * Additional information about the current status
     */
    statusMessage?: pulumi.Input<string>;
    /**
     * Whether to wait for the VPC peering connection to be active
     */
    waitForActive?: pulumi.Input<boolean>;
    /**
     * The timeout in minutes to wait for the VPC peering connection to be active
     */
    waitForActiveTimeout?: pulumi.Input<number>;
    /**
     * The timeout in minutes to wait for the VPC peering connection to be deleted. Set to 0 to disable waiting.
     */
    waitForDeletedTimeout?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a VpcPeeringConnectionAcceptance resource.
 */
export interface VpcPeeringConnectionAcceptanceArgs {
    /**
     * Identity of the VPC peering connection to accept
     */
    peeringConnectionId: pulumi.Input<string>;
    /**
     * Whether to wait for the VPC peering connection to be active
     */
    waitForActive?: pulumi.Input<boolean>;
    /**
     * The timeout in minutes to wait for the VPC peering connection to be active
     */
    waitForActiveTimeout?: pulumi.Input<number>;
    /**
     * The timeout in minutes to wait for the VPC peering connection to be deleted. Set to 0 to disable waiting.
     */
    waitForDeletedTimeout?: pulumi.Input<number>;
}
